### ISSUE TITLE
xxx-generated-istio-yaml has incorrect DaemonSet spec

### ISSUE THREAD

**Issue by kramerul** [cloudfoundry/cf-for-k8s#102]
If you look at [this line](https://github.com/cloudfoundry/cf-for-k8s/blob/d6252e2c89e2224742a0c55a40573866332ae3c9/config/_ytt_lib/github.com/cloudfoundry/cf-k8s-networking/config/istio-generated/xxx-generated-istio.yaml#L5853) and compare it to the API of [DaemonSet](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.16/#daemonsetspec-v1-apps) you can see that `strategy` is no valid spec element. It should be `updateStrategy`

Nether the less it seems that cf-for-k8s can be installed without error.

**Comment by jamespollard8** [comment]
Great catch - thanks for reporting it. @cloudfoundry/cf-networking could you please update to `updateStrategy`? Also, according to the docs, the `maxSurge` property might no longer be available.

**Comment by kramerul** [comment]
Could you please also enhance kapp, that it reports such Problems. It seems that kapp is ignoring unknown fields in the spec.

**Comment by jamespollard8** [comment]
> Could you please also enhance kapp, that it reports such Problems. It seems that kapp is ignoring unknown fields in the spec.

@cppforlife would it make sense to add such logic into `kapp`?

**Comment by cppforlife** [comment]
> Could you please also enhance kapp, that it reports such Problems. It seems that kapp is ignoring unknown fields in the spec.

kapp doesnt do anything about contents of the resource. it strictly relies on k8s api to give your errors with resources. im not sure why k8s api doesnt throw some error about unkown field...

**Comment by kauana** [comment]
> Great catch - thanks for reporting it. @cloudfoundry/cf-networking could you please update to `updateStrategy`? Also, according to the docs, the `maxSurge` property might no longer be available.

@jamespollard8 thanks for letting us know. It seems that DaemonSets doesn't have a `maxSurge` field after all so we will update that as well.

**Comment by acosta11** [comment]
Fixed by #124 which is now pushed to master in c23c954 .

Thanks,
Andrew and @ericpromislow (Community Pair)
