### ISSUE TITLE
cf-for-k8s fails to install with insufficient cpu

### ISSUE THREAD

**Issue by acosta11** [cloudfoundry/cf-for-k8s#103]
## Summary
The cluster requirements spec in the deploy documentation is out of date as of fdea7cea6c7299368037e5c1f3861cdbac7f8a00 ; the nodes do not have enough compute resources to deploy cf-for-k8s consistently.

## Steps to Reproduce
1. Provision a cluster according to the `deploy.md` doc: 5 nodes using the n1-standard-2 machine type on GKE (2 CPU and 7.5 GB memory).
1. Follow the remaining deploy steps to generate a values file for the deployment `my-values.yml` .
1. Run the `install.sh` script with my values file. `./install.sh my-values.yml`
1. See that the `kapp deploy` command times out with the following output:
```
...
Pending: Unschedulable (message: 0/5 nodes are available: 1 Insufficient cpu, 4 node(s) didn't match node selector.)
ok: waiting on pod/fluentd-qghm9 (v1) namespace: cf-system
ok: waiting on pod/fluentd-mkcxp (v1) namespace: cf-system
ok: waiting on pod/fluentd-kgcjn (v1) namespace: cf-system
ok: waiting on pod/fluentd-jrcxn (v1) namespace: cf-system
ok: waiting on controllerrevision/fluentd-6d89fcd764 (apps/v1) namespace: cf-system

kapp: Error: timed out waiting after 15m0s
```
## Solution
Updating the cluster to use a node pool with the n1-standard-4 machine type on GKE (4CPU 15 GB memory) caused the issue to go away as there were again enough compute resources to schedule everything in cf-for-k8s. Checking the node use after the succesful deploy showed that only a max of around 2.3 CPU resources were actually in use on each of the nodes. Update the Kubernetes Cluster Requirements to reflect a new minimum that satisfies the 2.3 constraint.

**Comment by kramerul** [comment]
Hi @acosta11,

this solution is not really practical. We always run into this issue when we use clusters with automatic scaling (gardener).
It would be more mature to change the deployment sequence inside kapp.
DaemonSets should be deployed before all other Pods, StatefulSets or Deployments. In that case, there should be enough resources to schedule the DaemonSet on every node.
Helm also deploys DaemonSets first.

**Comment by loewenstein** [comment]
Maybe an even better strategy would be to use pod priority classes and give DaemonSets a slightly higher priority than default. That way we wouldn't introduce any kind of deploy tool or deploy order dependency and it would be accounted for also if not currently deploying or updating.

**Comment by acosta11** [comment]
@kramerul and @loewenstein Thanks for the suggestions! I think you're both right here and our resource priorities should be updated to optimize for more realistic scaling and deployment strategies. Do you feel this warrants a reopening or recreation of this issue? Initially I created this issue for discoverability and assumed that cf-for-k8s would ultimately need the additional resources relative to the cluster size at the time. Currently, the team is largely avoiding autoscaling mechanisms and haven't really prioritized load testing as we still need general feature parity and operational tooling. This seems like the sort of optimization we should do before any production use; cc @cloudfoundry/cf-release-integration for visibility.

Thanks,
Andrew

**Comment by loewenstein** [comment]
I think @phil9909 worked on an overlay for FluentD in https://github.com/akhinos/cf-for-k8s-gardener/commit/e4c70ef72645bd9f8629e451c110a2922854c056 and once this is working as expected we'll forge it into a PR.

**Comment by phil9909** [comment]
I manually verified that a `PriorityClass` solves the issue by provoking the situation and it did. Then I created that overlay which add to `PriorityClass`es to every `DaemonSet` in cf-for-k8s. I would wait some time to verify the issue is really gone and then open a PR.

**Comment by davewalter** [comment]
Thanks @phil9909 & @loewenstein. In the meantime, we created an [exploration story](https://www.pivotaltracker.com/story/show/172461945) in our backlog for us to do our own investigation.

**Comment by cppforlife** [comment]
+1 for PriorityClass

though be careful with db migration Jobs. i would recommend to add another priority class that makes Jobs more important.
