### ISSUE TITLE
CAPI images are not pinned to a digest

### ISSUE THREAD

**Issue by Syerram** [cloudfoundry/cf-for-k8s#106]
## Expected behavior
CAPI images are pinned to a SHA digest.

## Actual behavior
CAPI images are pulling the latest images. This will result in non-deterministic cf-for-k8s deployments.
See this [config](https://github.com/cloudfoundry/cf-for-k8s/blob/master/config/_ytt_lib/github.com/cloudfoundry/capi-k8s-release/values.yml#L7). Lines 7 and 8 highlighted
```
  nginx: cloudfoundry/capi:nginx
  capi_kpack_watcher: cloudfoundry/capi-kpack-watcher:latest
```
## Context
As we plan to release cf-for-k8s 0.1 version, we need to ensure components are properly pinned.

**Comment by davewalter** [comment]
Fixed by https://github.com/cloudfoundry/cf-for-k8s/commit/8946c1488920e59759cddd60eb8e53d1b7be224b
