### ISSUE TITLE
Metacontroller is using a version tag instead of a digest

### ISSUE THREAD

**Issue by Syerram** [cloudfoundry/cf-for-k8s#107]
## Expected behavior
Metacontroller image is pinned to an SHA digest.

## Actual behavior
Metacontroller image is tagged to a semvar version instead of an SHA digest
See this [config](https://github.com/cloudfoundry/cf-for-k8s/blob/f419a7e41cd22df1162829d5d242c10a9dc6395d/config/_ytt_lib/github.com/GoogleCloudPlatform/metacontroller/manifests/metacontroller.yaml#L67). Lines 67 is highlighted below
```
      - name: metacontroller
         image: metacontroller/metacontroller:v0.4.0
```
## Context
As we plan to release cf-for-k8s 0.1 version, we need to ensure components are properly pinned to a digest.

**Comment by davewalter** [comment]
This was addressed by https://github.com/cloudfoundry/cf-for-k8s/commit/677a6456cd00ccac0f2f5e4f66fd483a6e3b49cb.
