### ISSUE TITLE
cf-for-k8s stores postgres db creds in configmap instead of secrets

### ISSUE THREAD

**Issue by Syerram** [cloudfoundry/cf-for-k8s#109]
### Context
@cppforlife noticed that we are storing passwords in `ConfigMap` to [bootstrap](https://github.com/cloudfoundry/cf-for-k8s/blob/a7f8bbf94b8a1da3a51826e58032287528a89315/config/postgres.yml#L50-L52) postrgesql DB. Ideally, passwords should be stored in `Secret` and not in  `ConfigMap`, since the latter stores them in plain text.

## Expected behavior
Postgresql passwords should be stored in a `Secret`

**Comment by davewalter** [comment]
Fixed by #114
