### ISSUE TITLE
Ability to bind a service from a service catalog is not supported

### ISSUE THREAD

**Issue by cmoulliard** [cloudfoundry/cf-for-k8s#115]
## Question/Discussion

One of the cool feature of the `CF` client and `Cloudfoundry` is that we can easily and quickly bind a service (PostgreSQL database, ...) to an application (Spring Boot, ....).

Unfortunately this option is not available using `cf-4-ks` as no Bitnami Helm Chart catalog or Service Catalog is deployed. By consequence, we cannot use `cf marketplace` or `cf services` to search a service and next bind it to an application

Question:
- What do you plan to do to support the following use case - see hereunder description ?

_As a user, I'm interested to install a Java application, next a DB such as MySQL, PostgeSQL, ... using a helm chart from a catalog or service using a Service Catalog/Broker and finally use `cf binding` (see : https://github.com/cloudfoundry-samples/spring-music#creating-and-binding-services) to bind/inject the parameters to configure the Java Datasource accessing the database_

- Will CloudFoundry and `cf bind` work using bitnami Helm charts catalog ?

**Comment by aegershman** [comment]
It's been purely experimental for me and I haven't leveraged it in a production environment by any means, but, at least as an example--

I've had success with registering [minibroker](https://github.com/kubernetes-sigs/minibroker#installation) with the cf marketplace and been able to [bind applications running on cf-for-k8s to services provisioned with it](https://github.com/aegershman/deployments/blob/master/cf-for-k8s/Taskfile.yml#L62-L71)

This isn't a comprehensive or conclusive answer by any means, just sharing one example

**Comment by cmoulliard** [comment]
@aegershman I also succeeded to deploy minibroker & bind a database as service : https://github.com/halkyonio/r-d/blob/master/cloudfoundry/DEVELOPER.md#deploy-a-spring-application-accessing-a-database

**Comment by loewenstein** [comment]
Is this about cf-for-k8s coming with batteries included? I don't think this can ever be more than trial experience, managing databases is hard and beyond what CF can offer imho.

**Comment by jamespollard8** [comment]
This works now as long as your platform is configured with real certs.
