### ISSUE TITLE
Cannot view metrics with the cf7 cli

### ISSUE THREAD

**Issue by zrob** [cloudfoundry/cf-for-k8s#122]
Currently both `cf7 push` and `cf7 apps` fail with the same error message.

```
Stats unavailable: Stats server temporarily unavailable.
FAILED
```

Both of these commands ran successfully at checksum `a7f8bbf`

**Comment by hev** [comment]
I was not able to reproduce this when I tested with cf7 and included #92

**Comment by zankich** [comment]
This is probably related to https://github.com/cloudfoundry/cf-for-k8s/issues/123#issuecomment-613641176

**Comment by Birdrock** [comment]
Closing in favor of https://github.com/cloudfoundry/cf-for-k8s/issues/123#issuecomment-613641176
