### ISSUE TITLE
Smoke test race condition when run in parallel

### ISSUE THREAD

**Issue by jenspinney** [cloudfoundry/cf-for-k8s#144]
# Context
In [this commit](https://github.com/cloudfoundry/cf-for-k8s/commit/27a59a24db3f140a360c11debcc9e49f9d62d981), the smoke tests were changed so that one test enables the `diego_docker` feature flag and the other one disables it. If the tests are run in parallel, this makes it likely that one of the two tests will fail.

# Problem
On the CF-K8s Networking team, we had been (maybe inadvertently) been relying on these smoke tests to enable the diego-docker feature flag for follow-on tests in our CI. When this change went through, our tests were failing because of that assumption no longer being true. We're fixing our own CI anyway to not have this dependency, but we did notice when we looked at the change that it:
1. means the tests won't reliably succeed when run in parallel, and
2. it leaves the testing environment in a non-deterministic state because we can't know which test run last, and therefore whether the feature flag was left on or not. 

# Suggestion
Ideally, we won't need these custom smoke tests at all and we can just use the "regular" [cf smoke tests](https://github.com/cloudfoundry/cf-smoke-tests). I believe this will probably just take some time for the binary buildpack functionality (aka the "procfile" buildpack in the Cloud Native Buildpack world) to make its way to cf-for-k8s.

In the interim, I wonder if the docker-app test is even needed. Pushing docker apps is not a feature of the "regular" smoke tests. On rel-int, we added it originally because there was no ability to push buildpack apps at all.

Thanks,
Jen & @XanderStrike

**Comment by jamespollard8** [comment]
I like the idea of removing the docker-app test. We've kicked off a slack discussion for this [here](https://cloudfoundry.slack.com/archives/CH9LF6V1P/p1586988147392800)

**Comment by KauzClay** [comment]
Heyo,

We read the slack conversation and it looks like we never reached a decision. We also see that this was moved from `scheduled` to `unscheduled`. 

Should we just close this issue?

Thanks!
@KauzClay @XanderStrike

**Comment by jamespollard8** [comment]
Thanks for the bump.

I talked with some teammates and we've decided to simply remove the docker image-based app. https://github.com/cloudfoundry/cf-for-k8s/commit/fa03a426be5719766fc4eeccad763f7a4cd81c4e
