### ISSUE TITLE
[0.1.0] release notes & docs -- please state the http-only limitation for apps

### ISSUE THREAD

**Issue by drnic** [cloudfoundry/cf-for-k8s#148]
In release v0.1.0 and from tracker [1] we don't yet have HTTPS for apps. That's not at all obvious when you first tentatively deploy CF and deploy the first app and your first experience of viewing the app in a browser (which will be via HTTPS by default) is a blank page and a quiet 404 error when you check the HTTPS url via `curl`.

On the plus side, this bug lead me to learn about the two different ingress gateways for cf-system and cf-workloads, and how the latter is only configured for `:80` at the moment. And then I found the tracker ticket.

But it might be worth adding "Known issues: apps only accessible via HTTP at the moment, please see tracker [1]" to the release notes for v0.1.0 and the README/docs (see PR #149)

[1] https://www.pivotaltracker.com/n/projects/1382120/stories/171482241

**Comment by davewalter** [comment]
Closing per https://github.com/cloudfoundry/cf-for-k8s/pull/149#issuecomment-615381745
