### ISSUE TITLE
Env variables are not passed to kpack builds

### ISSUE THREAD

**Issue by kramerul** [cloudfoundry/cf-for-k8s#163]
### Summary

Some buildpacks [require environment variables](https://github.com/paketo-buildpacks/bellsoft-liberica#configuration) for configuration. But they are not passed to the [kpack build](https://github.com/pivotal/kpack/blob/master/docs/build.md#configuration)

As you can see [in the code](https://github.com/cloudfoundry/cloud_controller_ng/blob/a904b8dee962f9edfa143490d4530968b5598bce/lib/cloud_controller/kpack/stager.rb#L67-L80) no environment variables are passed.
### Reproduction Steps

Push a java application with *$BP_JAVA_VERSION=8.*"

### Expected behavior

_What was the expected result?_

The configuration variable is taken into account.

**Comment by davewalter** [comment]
Hi @kramerul,

Thanks for reporting this. It is worth noting that we are still in the early stages of getting specific features of CloudFoundry to work with cf-for-k8s, but it is also worth noting them as you encounter missing functionality. 

For CAPI-specific issues, could you please report them directly against the [capi-k8s-release](https://github.com/cloudfoundry/capi-k8s-release) repository?

Thanks,
Dave

**Comment by loewenstein** [comment]
@davewalter I suppose that someone with the right permissions could move this over to the capi-k8s-release repo.

**Comment by kramerul** [comment]
I moved it to https://github.com/cloudfoundry/capi-k8s-release/issues/37
