### ISSUE TITLE
cf pushed apps cannot make outgoing http network requests for the first few seconds

### ISSUE THREAD

**Issue by cfryanr** [cloudfoundry/cf-for-k8s#167]
### Summary

cf pushed apps cannot make outgoing http network requests for the first few seconds. They almost always result in `Connection refused` socket errors.

### Reproduction Steps
Using cf-for-k8s v0.1.0 deployed on GKE with k8s version 1.14.10-gke.27

Please see the README at https://github.com/cfryanr/network-demo for full details and reproduction steps, along with a simple app which can be pushed to demonstrate the problem.

**Comment by rosenhouse** [comment]
would it suffice to add the wildcard domains ([cf-deployment config](https://github.com/cloudfoundry/cf-deployment/blob/50cfcf63e94b678a932516c277ece755cf1a140d/cf-deployment.yml#L717-L721)) to the [list of hosts in this virtualservice](https://github.com/cloudfoundry/cf-for-k8s/blob/master/config/uaa.yml#L235-L236)?

seems like something the UAA team could test out using `kubectl edit` on their cluster, and if it works, open a PR to this repo?

**Comment by jpalermo** [comment]
Closing due to duplicate #189 which currently has more context on it.
