### ISSUE TITLE
Add UAA subdomains as subject alt names in system cert

### ISSUE THREAD

**Issue by cfryanr** [cloudfoundry/cf-for-k8s#175]
### Summary

Hi @davewalter and @acosta11 and team,

I'm sorry to effectively reopen issue #170, but I forgot that we would also need to add `*.uaa.system-domain` and `*.login.system-domain` to the Subject Alt Name of the system's ingress TLS certificate.

It can be done like this: https://github.com/cfryanr/cf-for-k8s/commit/cbb496b64929c4f6500af89d03793ee770d116fb

I'm not sure if there is any corresponding documentation for operators to update as well? I suppose operators who want to create their own TLS certificate should know which SANs to put into the certificate that they create, but I couldn't find any such docs to update.

**Comment by davewalter** [comment]
No worries @cfryanr. I committed the change here: https://github.com/cloudfoundry/cf-for-k8s/commit/36616596a9891028d8ef1e7f4352d25f93b2969e
