### ISSUE TITLE
Metrics fail to display after rolling application update

### ISSUE THREAD

**Issue by zrob** [cloudfoundry/cf-for-k8s#177]
After pushing an app it is possible to view metrics using `cf app my-app`

<img width="542" alt="Screen Shot 2020-05-03 at 3 48 11 PM" src="https://user-images.githubusercontent.com/1703742/80927896-a6e54000-8d55-11ea-8010-1260da02020a.png">

A followup `cf push` to update the app also eventually displays metrics as shown above.

However, using cf7 to `cf push my-app --strategy rolling` the metrics will never display as anything other than zero.

<img width="519" alt="Screen Shot 2020-05-03 at 3 54 52 PM" src="https://user-images.githubusercontent.com/1703742/80928012-823d9800-8d56-11ea-8d61-5f090ff12cbf.png">

Note that when reproducing the successful case it is necessary to wait for metrics to display due to metric scraping intervals.

**Comment by Syerram** [comment]
Metrics team is reviewing this issue => https://www.pivotaltracker.com/story/show/172660947

Tagging @hev

**Comment by kkburr** [comment]
After investigating, we discovered that the metrics-server stores system metrics for pods by guid, not app_guid (which is what our code was selecting)

`cf push` -ing multiple times creates a new pod for the app instance, but it sends the same app_guid and guid values. metric-proxy is matching on app_guid and was able to find the pod.

`cf7 push` -ing multiple times does the same thing as above ^

`cf7 push` -ing multiple times with --strategy rolling creates a new pod with a new app_guid, but preserves the original guid. Switching our code to select on guid finds the pod metrics; using app_guid never finds it.

Our team will PR this into cf-for-k8s today.

**Comment by jamespollard8** [comment]
Closed by #195
