### ISSUE TITLE
cf-for-k8s no longer works on kind with 4 cores and 8GB RAM

### ISSUE THREAD

**Issue by jamespollard8** [cloudfoundry/cf-for-k8s#181]
### Summary

We're no longer able to deploy on kind from `v0.2.0` or from `master`.

here's the `kapp deploy` error I see:
```
11:37:49PM: ongoing: reconcile deployment/capi-deployment-updater (apps/v1) namespace: cf-system
11:37:49PM:  ^ Waiting for 1 unavailable replicas
11:37:49PM:  L ok: waiting on replicaset/capi-deployment-updater-7f4f499d5d (apps/v1) namespace: cf-system
11:37:49PM:  L ongoing: waiting on pod/capi-deployment-updater-7f4f499d5d-km2r9 (v1) namespace: cf-system
11:37:49PM:     ^ Condition Ready is not True (False)
11:37:50PM: ongoing: reconcile deployment/metric-proxy (apps/v1) namespace: cf-system
11:37:50PM:  ^ Waiting for 1 unavailable replicas
11:37:50PM:  L ok: waiting on replicaset/metric-proxy-769c86b94b (apps/v1) namespace: cf-system
11:37:50PM:  L ongoing: waiting on pod/metric-proxy-769c86b94b-qxsvg (v1) namespace: cf-system
11:37:50PM:     ^ Condition Ready is not True (False)
11:37:51PM: fail: reconcile deployment/istio-pilot (apps/v1) namespace: istio-system

kapp: Error: waiting on reconcile deployment/istio-pilot (apps/v1) namespace: istio-system: finished unsuccessfully (Deployment is not progressing: ProgressDeadlineExceeded (message: ReplicaSet "istio-pilot-5d7f49b7f" has timed out progressing.))
```

### Reproduction Steps
1) Checkout master and pull latest changes

2) Set docker desktop settings to 4+ CPU and 8+ GB ram.

3) Create a kind cluster with
```
cd cf-for-k8s
kind create cluster --config=./deploy/kind/cluster.yml --image kindest/node:v1.16.4
```

4) Follow documentation for deploying kind, running this kapp deploy:
`kapp deploy -a cf -f <(ytt -f config -f ${values_file} -f config-optional/remove-resource-requirements.yml -f config-optional/remove-ingressgateway-service.yml) -y`

### Expected behavior

The deploy should succeed and smoketests should pass.

**Comment by heycait** [comment]
This may be because we haven't bumped `metric-proxy`. Looks like it's using https://github.com/cloudfoundry/metric-proxy/commit/614dbcd1a80512fb707f936067d8c498e3471682 which had this issue: https://github.com/cloudfoundry/metric-proxy/pull/2

**Comment by jamespollard8** [comment]
>This may be because we haven't bumped metric-proxy. Looks like it's using cloudfoundry/metric-proxy@614dbcd which had this issue: cloudfoundry/metric-proxy#2

Oh, that's interesting but I don't think it's the root issue.

I increased by Docker Desktop resources to 7 CPU and 14 GB RAM (my machine has 8 CPU and 32 GB RAM) and now things are working for me again.

**Comment by jamespollard8** [comment]
I've updated the docs accordingly

**Comment by cmoulliard** [comment]
> I've updated the docs accordingly

Can you link here the PR or commit link please @jamespollard8 regarding the documentation change ?

**Comment by jamespollard8** [comment]
Sure thing https://github.com/cloudfoundry/cf-for-k8s/commit/37eab8fc9e1204278855ad7fb19c4dfe81c818e9
