### ISSUE TITLE
ccdb-migrate timeouts and <cf api> fails due to 502 Bad Gateway

### ISSUE THREAD

**Issue by heycait** [cloudfoundry/cf-for-k8s#182]
### Summary

`kapp deploy` times out at ccdb-migrate. While the rest of the install looks okay. Trying to proceed with this deploy, I am then unable to target CF using `cf api`. It fails with the following message:

```
$ cf api --skip-ssl-validation https://api.wash-park.loggr.cf-app.com
Setting api endpoint to https://api.wash-park.loggr.cf-app.com...
Error unmarshalling the following into a cloud controller error: <html>
<head><title>502 Bad Gateway</title></head>
<body>
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx</center>
</body>
</html>

FAILED
```

### Reproduction Steps
[tag v0.2.0](https://github.com/cloudfoundry/cf-for-k8s/tree/v0.2.0)

Followed the install commands in:https://github.com/cloudfoundry/cf-for-k8s/blob/master/docs/deploy.md. Did `ytt -f config...` followed by `kapp deploy ...` and updating the appropriate DNS.

[IaaS name(s) here (GKE, AKS, EKS, minikube, kind, etc)]
GKE

[Kubernetes version here]
1.14.10-gke.27

[Special configuration here]
N/A

_What steps/actions led to the issue?_
After rendering the cf values and kapp deploy, the deploy times out after 15m of trying to complete `ccdb-migrate` job.

```
9:41:43PM: ---- waiting on 1 changes [253/254 done] ----
9:42:09PM: ongoing: reconcile job/ccdb-migrate (batch/v1) namespace: cf-system
9:42:09PM:  ^ Waiting to complete (1 active, 0 failed, 0 succeeded)
9:42:09PM:  L ongoing: waiting on pod/ccdb-migrate-vxpxp (v1) namespace: cf-system
9:42:09PM:     ^ Pending: PodInitializing

kapp: Error: timed out waiting after 15m0s
```

Since all the other pods are running successfully, I tried to continue using this environment and targeting it. However it results in the 502 Bad Gateway. Looking at the nginx logs, this is the error:

```
2020/05/05 21:50:16 [crit] 8#0: *203 connect() to unix:/data/cloud_controller_ng/cloud_controller.sock failed (2: No such file or directory) while connecting
to upstream, client: 127.0.0.1, server: , request: "GET /v3/routes?per_page=5000 HTTP/1.1", upstream: "http://unix:/data/cloud_controller_ng/cloud_controller.
sock:/v3/routes?per_page=5000", host: "capi.cf-system.svc.cluster.local"
2020/05/05 21:50:19 [crit] 8#0: *236 connect() to unix:/data/cloud_controller_ng/cloud_controller.sock failed (2: No such file or directory) while connecting
to upstream, client: 127.0.0.1, server: , request: "GET /v2/info HTTP/1.1", upstream: "http://unix:/data/cloud_controller_ng/cloud_controller.sock:/v2/info",
host: "api.wash-park.loggr.cf-app.com"
```

### Expected behavior

`kapp deploy` succeeds and I am able to target CF using `cf api`

**Comment by jamespollard8** [comment]
Here's our slack thread with a good amount of back-and-forth: https://cloudfoundry.slack.com/archives/CH9LF6V1P/p1588715132232300?thread_ts=1588715006.232200&cid=CH9LF6V1P

**Comment by heycait** [comment]
I create a new cluster with a completely different name and didn't encounter this issue. The previous attempt above was reusing a cluster name (i.e. deleting wash-park cluster, creating new wash-park cluster then following deploy steps).

**Comment by jamespollard8** [comment]
Cool, I'll close out this issue 👍
