### ISSUE TITLE
Can't push golang apps anymore

### ISSUE THREAD

**Issue by jspawar** [cloudfoundry/cf-for-k8s#184]
### Summary

Used to be able to push catnip app to a cf-for-k8s deployment and discovered that I no longer can with a consistent failure attached below.

### Reproduction Steps
[cf-for-k8s sha hyperlink here]
21209bbfcadf626a81bc19a8320050b98076f25e

[Please include the `kapp deploy...` command, including all `config-optional` files]
`kapp deploy -a cf -f <(ytt -f config/ -f my-values.yml)`

[IaaS name(s) here (GKE, AKS, EKS, minikube, kind, etc)]
AKS

[Kubernetes version here]
v1.15.10

_What steps/actions led to the issue?_
1. `cf push catnip -p ~/workspace/cf-acceptance-tests/assets/catnip`

_It's helpful to include snippets of the error response or logs output_
```bash
±  |master ✓| → cf push catnip
Pushing app catnip to org o / space s as admin...
Getting app info...
Creating app with these attributes...
+ name:       catnip
  path:       /Users/me/workspace/cf-acceptance-tests/assets/catnip
  routes:
+   catnip.aks.k8s.capi.land

Creating app catnip...
Mapping routes...
Comparing local files to remote cache...
Packaging files to upload...
Uploading files...
 1.16 MiB / 1.16 MiB [================================================================================================================== 1.16 MiB / 1.16 MiB [======================================================================================================] 100.00% 1s

Waiting for API to complete processing files...

Staging app and tracing logs...
   prepare:fetch.go:74: Successfully downloaded cf-blobstore-minio.cf-blobstore.svc.cluster.local:9000/cc-packages/d2/8e/d28e16d9-d9ff-4340-8fc7-63009417a993 in path "/workspace"
   org.cloudfoundry.go-compiler 0.0.105
   org.cloudfoundry.dep         0.0.101
   Previous image with name "gcr.io/cf-capi-arya/cf-workloads/fd4a2470-436d-46ba-a0ed-c62bb37d463f" not found

   Go Compiler Buildpack 0.0.105
   Go 1.13.9: Contributing to layer
       Downloading from https://buildpacks.cloudfoundry.org/dependencies/go/go-1.13.9-bionic-61a279e8.tgz
       Verifying checksum
       Expanding to /layers/org.cloudfoundry.go-compiler/go

   Dep Buildpack 0.0.101
       failure running build: no import-path found in buildpack.yml
   ERROR: failed to build: exit status 102
Error staging application: Stager error: Kpack build failed
FAILED
```

### Expected behavior

Expected push to succeed and be able to route traffic to that app

**Comment by jamespollard8** [comment]
FWIW this works for me on kind with current head of develop. I'm wondering if this is AKS-specific

**Comment by davewalter** [comment]
Which sha of CATs are you both using? @jspawar's output includes `Dep Buildpack 0.0.101`, whereas @jamespollard8's has `Go Mod Buildpack 0.0.89`, which makes me wonder if there is a problem with the `Go.dep` detection in the Go buildpack.

Is it possible that you are using an old sha of CATs @jspawar?

**Comment by jamespollard8** [comment]
Good catch Dave. I'm using `v5.10.0`, current head of develop

**Comment by jspawar** [comment]
Oh yea good catch @davewalter, I'm using a very old commit of `cf-acceptance-tests`: `2dbbedeb3eb2008c9a5b364f36bd567382e07e89` (from March 2019)

Used the latest version of `catnip` and it was working as expected. Think it might be related to that Dep buildpack then like you said. 

Should we pull in kpack folks? Or would you like me to close this and move to their GitHub repo?

**Comment by jamespollard8** [comment]
👍 Please do close this out and move it over to their repo. It's helpful for our backlog management to close out stories that don't require remaining action from our team.
