### ISSUE TITLE
cf-domain needs to be highlighted as a sys domain. Have a separate domain for apps.

### ISSUE THREAD

**Issue by msathe-tech** [cloudfoundry/cf-for-k8s#200]
### Summary
./hack/generate-values.sh -d <cf-domain>
README needs to clearly state that the domain needs to be a SYS domain. 
So it will sys.<your-hosted-zone-domain-name> 
### Reproduction Steps
At least 3 hosts are required - login, api and uaa
So, unless you specify SYS domain and use *.sys DNS entry you will run into several issues interacting with cf-4-k8s. 
[Special configuration here]

_What steps/actions led to the issue?_

_It's helpful to include snippets of the error response or logs output_

### Expected behavior
Have a separate domain for SYS and Apps urls. generate-values.sh should take these two inputs. Changing values in /tmp/cf-values.yml is not going to help because the Certs will need to be regenerated.  
User should then make two DNS entries - *.sys.<cf-domain> and *.apps.<cf-domain>
_What was the expected result?_

**Comment by loewenstein** [comment]
We **do** run a couple of CF applications in in the system domain. That being that, as long as using the system domain for apps stays a supported scenario, it should be fine with defaulting to separate domains.

**Comment by acosta11** [comment]
Hello @msathe-tech ,

> So, unless you specify SYS domain and use *.sys DNS entry you will run into several issues interacting with cf-4-k8s.

What issues in particular are you running into that rely on a `*.sys.cf-for-k8s-base-domain` configuration? In our CI pipeline, we use the `*.cf-for-k8s-base-domain` domain for our system components without issue.

Thanks,
Andrew and @davewalter

**Comment by msathe-tech** [comment]
There are two issues -
1. The README is not clear that <cf-domain> needs to be a SYS domain (Pivotal docs asks to create SYS domain)
2. Unless there is a *.sys or something similar you will end up adding separate DNS entries for api, uaa, etc. And I've found out that the there is a lag between nslookup showing name resolved and cf cli being able to do it. For some reason, cf login was failing to resolve the name even though nslookup showed result.

**Comment by msathe-tech** [comment]
Moreover, as a good practice, it is imp to separate SYS and Apps domains. That what we do in PAS today.

**Comment by acosta11** [comment]
> Unless there is a *.sys or something similar you will end up adding separate DNS entries for api, uaa,

Are separate DNS entries required for api and uaa when istio ingress routing resolves that traffic on subdomains of the cf-for-k8s domain? (I haven't had to set up a full production environment or in general an environment with so many DNS entries yet, so am genuinely not familiar) What is the goal of separate DNS entries in this case?

> The README is not clear that needs to be a SYS domain (Pivotal docs asks to create SYS domain)

What docs in particular ask for a sys domain? I can point our PM in that direction to see if we're trying to keep the README consistent.

**Comment by jpalermo** [comment]
Thanks for submitting the issue and working with us. We're going to close it for now, but feel free to reopen it as you see fit.
