### ISSUE TITLE
Unable to use a real cert with cf-for-k8s

### ISSUE THREAD

**Issue by Syerram** [cloudfoundry/cf-for-k8s#204]
### Summary

I cannot set a real cert for cf-for-k8s (both API and app domain). See investigation on this issue [here](https://www.pivotaltracker.com/story/show/172758668)

### Reproduction Steps
See the steps given in the above story.

### Expected behavior
I should be able to use a real cert with cf-for-k8s.

### Technical details
After speaking to @davewalter, we should separate the ingress certs from the system component certs in the install values yml. This will be a temporary stop-gap solution and the plan is to remove the component certs and rely on istio to manage the certs.

**Comment by davewalter** [comment]
See #205 for a proposed short-term solution.

**Comment by jamespollard8** [comment]
Fixed by https://github.com/cloudfoundry/cf-for-k8s/pull/205

**Comment by jamespollard8** [comment]
We dropped some instructions for doing this here:
https://www.pivotaltracker.com/story/show/172758668/comments/214697442
