### ISSUE TITLE
During upgrade, `kapp` returns without waiting for postgres statefulset to become healthy

### ISSUE THREAD

**Issue by Syerram** [cloudfoundry/cf-for-k8s#206]
### Summary
When upgrading the postgresdb, kapp immediately returns instead of waiting for postgresdb statefulset to become operational again. 

Due to this UX issue, the user may assume that the database is up and running and perform cf push and fail. 

### Reproduction Steps
- Run `kapp deploy -a cf cf-for-k8s-rendered.yml` that contains the latest postgres db bump.
- Watch kapp return immediately but the postgres db pod in `cf-db` namespace is still not up and running

### Expected behavior
`kapp` waits till the postgresdb pod is healthy. Please note that the database upgrade is successful, found no data loss and cf-push works after upgrade.

### Other details
Tagged as a known issue.

**Comment by acosta11** [comment]
With the default wait rule implemented in kapp, we can now update our minimum required kapp version and validate that issue is resolved.
