### ISSUE TITLE
Install fails because Istio images require privileged access

### ISSUE THREAD

**Issue by msathe-tech** [cloudfoundry/cf-for-k8s#208]
### Summary

_In your own words, describe the issue._
Istio images need to run as Root and it is prevented on TKG on AWS. 
### Reproduction Steps
[cf-for-k8s sha hyperlink here]
1. Create a TKS cluster on AWS
2. Follow the steps in this README to setup TAS on K8s. 

[Please include the `kapp deploy...` command, including all `config-optional` files]

[IaaS name(s) here (GKE, AKS, EKS, minikube, kind, etc)]

output of `ytt --version ; kapp --version ; kubectl version`:
[paste output here]
L ongoing: waiting on pod/istio-policy-7768c9dbc4-mdpzj (v1) namespace: istio-system
11:35:00AM:     ^ Pending: CreateContainerConfigError (message: container has runAsNonRoot and image will run as root)
...
11:35:04AM:  L ongoing: waiting on pod/istio-citadel-757d677f57-s64dz (v1) namespace: istio-system
11:35:04AM:     ^ Pending: CreateContainerConfigError (message: container has runAsNonRoot and image will run as root)

[Special configuration here]

_What steps/actions led to the issue?_

_It's helpful to include snippets of the error response or logs output_

### Expected behavior

_What was the expected result?_

**Comment by acosta11** [comment]
Hello,

As I'm not too familiar with the exact requirements of istio, I reached out to some of folks contributing to cf-for-k8s-networking in the cf-for-k8s channel in the cloudfoundry slack. It sounds like the current state of istio config requires us to include at least one root user, so we'll likely need a solution for running as root on tkg/aws for an immediate workaround. Leaving this issue open and marking as a known issue while we get a better idea of the solution.

Thanks,
Andrew

**Comment by jamespollard8** [comment]
This was fixed a while back - closing
