### ISSUE TITLE
Rotating non-admin user/role credentials in postgres fails

### ISSUE THREAD

**Issue by Syerram** [cloudfoundry/cf-for-k8s#216]
### Summary
Rotating non-admin user/role credentials in postgres fails to upgrade.

### Reproduction Steps
When I deploy postgres with a different password for the ccdb or uaa user, that change is NOT reflected in postgres. Due to this, the capi and uaa clients respectively cannot connect with the new credentials.

### Expected behavior
Expect postgres ccdb and uaa user passwords are propagated to the pods.

**Comment by jamespollard8** [comment]
This is covered by more specific issues for the specific credentials that are not yet rotate-able. Closing
