### ISSUE TITLE
`kapp delete -a cf` fails with timeout

### ISSUE THREAD

**Issue by Syerram** [cloudfoundry/cf-for-k8s#224]
### Summary
`kapp delete -a cf` fails with timeout because it is unable to delete cf routes.

### Reproduction Steps
- deploy from master
- kapp deploy
- push an app
- kapp delete

### Expected behavior
`kapp delete -a cf` should pass.
Slack thread https://cloudfoundry.slack.com/archives/CFX13JK7B/p1591652485250100

### Proposed solution
1. Add `kapp` rule to delete the cf-workloads namespace before the routecontroller.
2. The next version of `kapp` will target crds first.

Since this is breaking our pipelines, we should implement option 1 as a stopgap.

@jamespollard8 @acosta11 @davewalter

**Comment by jamespollard8** [comment]
This has been fixed for a while. Next step is to remove the overlay we put in place because the `kapp` logic has since been improved.
