### ISSUE TITLE
The CC blobstore access key is stored as a plain text value to cloud-controller-ng-yaml configmap 

### ISSUE THREAD

**Issue by Syerram** [cloudfoundry/cf-for-k8s#227]
### Summary

- The CC blobstore access key is stored as a plain text value to the Cloud Controller config map [`cloud-controller-ng-yaml` ](https://github.com/cloudfoundry/cf-for-k8s/blob/4eb5ad6fbcd149a1f8f5e1e8ad90c7bde4450be7/config/_ytt_lib/github.com/cloudfoundry/capi-k8s-release/templates/ccng-config.lib.yml#L179) 

```yaml
    resource_pool:
      ...
      fog_connection:
        ...
        aws_access_key_id: admin
        aws_secret_access_key: 87scyz57wpwn13g38z6s
        aws_signature_version: "2"

```

- The CC config creates multiple blobstore directories and stores the access key as plain text value for each of the directory configs
  - [`resource_pool`](https://github.com/cloudfoundry/cf-for-k8s/blob/4eb5ad6fbcd149a1f8f5e1e8ad90c7bde4450be7/config/_ytt_lib/github.com/cloudfoundry/capi-k8s-release/templates/ccng-config.lib.yml#L179)
  - [`packages `](https://github.com/cloudfoundry/cf-for-k8s/blob/4eb5ad6fbcd149a1f8f5e1e8ad90c7bde4450be7/config/_ytt_lib/github.com/cloudfoundry/capi-k8s-release/templates/ccng-config.lib.yml#L200)
  - [`droplets `](https://github.com/cloudfoundry/cf-for-k8s/blob/4eb5ad6fbcd149a1f8f5e1e8ad90c7bde4450be7/config/_ytt_lib/github.com/cloudfoundry/capi-k8s-release/templates/ccng-config.lib.yml#L221)
  - [`buildpacks`](https://github.com/cloudfoundry/cf-for-k8s/blob/4eb5ad6fbcd149a1f8f5e1e8ad90c7bde4450be7/config/_ytt_lib/github.com/cloudfoundry/capi-k8s-release/templates/ccng-config.lib.yml#L241)

### Expected behavior
CAPI should use the k8s secret mechanism to consume the secret key. As per Kubernetes [docs](https://kubernetes.io/docs/concepts/configuration/secret/#using-secrets), the options are to either [mount them as files](https://kubernetes.io/docs/concepts/configuration/secret/#using-secrets-as-files-from-a-pod) or consume them as [environment variables](https://kubernetes.io/docs/concepts/configuration/secret/#using-secrets-as-environment-variables).

**Comment by matt-royal** [comment]
We've made this change in capi-k8s-release and cf-for-k8s.
