### ISSUE TITLE
CloudFoundry applications, with a route belonging to the system domain, do not get SSL

### ISSUE THREAD

**Issue by aashah** [cloudfoundry/cf-for-k8s#238]
### Summary

The current [ingressgateway configuration](https://github.com/cloudfoundry/cf-for-k8s/blob/7ea39592d3b9bab21c4dffb2e06636a399c9a76b/config/gateway.lib.yml) does not apply any SSL for apps pushed to the system domain. The system domain is usually seeded during the initial installation of the foundation (`cf domains`).

### Reproduction Steps

* any cf-for-k8s
* normal `kapp deploy` as documented in deploy guide

_What steps/actions led to the issue?_

1. Deploy a foundation
1. Push an app to the system domain
1. Observe no SSL

### Expected behavior

The app has SSL.

**Comment by aashah** [comment]
We got this working with the following patch to `gateway.lib.yaml`:

```diff
diff --git a/config/gateway.lib.yml b/config/gateway.lib.yml
index dfadcc4..bede6c1 100644
--- a/config/gateway.lib.yml
+++ b/config/gateway.lib.yml
@@ -17,6 +17,7 @@ spec:
       protocol: HTTP
   - hosts:
     - #@ ('' if system_domain in app_domains else system_namespace + '/') + '*.' + system_domain
+    - #@ workloads_namespace + '/*.' + system_domain
     port:
       name: https-system
       number: 443
```

**Comment by christianang** [comment]
From the Networking Team's standpoint this sounds fine. I think we can even go a step further and wildcard the namespace of the original hosts string e.g

```yaml
   - hosts:
     - */*.system_domain
```

Just double check that workloads on the app domain still use the workload certificate even if the app domain is a subdomain of the system domain i.e what we do by default `*.apps.system-domain`. We are pretty sure this should work though.

**Comment by aashah** [comment]
Tested this out against a new cluster with cf-for-k8s `f5c55ee`:

1. Modified the ingressgateway to be `*/*.system_domain` (left the workloads one alone). Snippet pasted below as well.
1. Deploy an app and map it to a route belonging to the system and apps domain.
1. Ensure the certificate is correct for each one.

Below, I've mapped an app to a route belonging to both domains. I show successful curls against both domains. I show the certificate for both are respectively correct.

```
~/workspace/cf-for-k8s develop*
❯ cf apps
Getting apps in org test / space test as admin...
OK

name   requested state   instances   memory   disk   urls
foo    started           1/1         1G       1G     foo.apps.aakash.domain, foo.aakash.domain

~/workspace/cf-for-k8s/tests/smoke/assets/test-node-app develop*
❯ curl https://foo.aakash.domain -k
Hello World

~/workspace/cf-for-k8s/tests/smoke/assets/test-node-app develop*
❯ curl https://foo.apps.aakash.domain -k
Hello World

~/workspace/cf-for-k8s/tests/smoke/assets/test-node-app develop* 6s
❯ echo -n | /usr/local/opt/openssl/bin/openssl s_client -showcerts -connect foo.aakash.domain:443 2>/dev/null | openssl x509 -inform pem -noout -text
Certificate:
    ...
    Signature Algorithm: sha256WithRSAEncryption
        ...
        Subject: C=USA, O=Cloud Foundry, CN=*.aakash.domain

~/workspace/cf-for-k8s/tests/smoke/assets/test-node-app develop*
❯ echo -n | /usr/local/opt/openssl/bin/openssl s_client -showcerts -connect foo.apps.aakash.domain:443 2>/dev/null | openssl x509 -inform pem -noout -text
Certificate:
    ...
    Signature Algorithm: sha256WithRSAEncryption
        Subject: C=USA, O=Cloud Foundry, CN=*.apps.aakash.domain
        ...
```

Will follow up with a PR soon!

**Comment by Syerram** [comment]
Fixed on the current master
