### ISSUE TITLE
Staging application fails with "pod already exists"

### ISSUE THREAD

**Issue by mnitchev** [cloudfoundry/cf-for-k8s#240]
### Summary

Running [this smoke test](https://github.com/cloudfoundry/cf-for-k8s/blob/master/tests/smoke/smoke_test.go#L87) yields the following error when trying to push: `Error staging application: Stager error: Kpack build failed. build failure message: 'pods "72f8ffec-de2d-4218-bf9c-c8aa2d2bf34d-build-1-l8k96-build-pod" already exists'.
`.  We (Eirini) run the smoke tests as part of our CI, with the latest eirini. Since we had a similar problem in eirini [here](https://github.com/cloudfoundry-incubator/eirini/issues/92) we suspect that this might be because the cloud controller's task_sync is also desiring the staging task and causing the conflict (or something similar).

### Reproduction Steps
[cf-for-k8s sha hyperlink here](https://github.com/cloudfoundry/cf-for-k8s/tree/v0.3.0)

IaaS name(s) here - GKE

output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.9", GitCommit:"a17149e1a189050796ced469dbd78d380f2ed5ef", GitTreeState:"clean", BuildDate:"2020-04-16T11:44:51Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.9-gke.2", GitCommit:"4751ff766b3f6dbf6c6a63394a909e8108e89744", GitTreeState:"clean", BuildDate:"2020-05-08T16:44:50Z", GoVersion:"go1.13.9b4", Compiler:"gc", Platform:"linux/amd64"}
```

_What steps/actions led to the issue?_
Running the smoke tests.

_It's helpful to include snippets of the error response or logs output_
```
cf push cf-for-k8s-smoke-1-app-73452f418909b043 -p assets/test-node-app --no-route 
Pushing app cf-for-k8s-smoke-1-app-73452f418909b043 to org cf-for-k8s-smoke-1-org-1e5ccacb057a11f6 / space cf-for-k8s-smoke-1-space-0ff151b397505534 as admin...
Getting app info...
Creating app with these attributes...
+ name:       cf-for-k8s-smoke-1-app-73452f418909b043
  path:       /tmp/build/a94a9454/cloudfoundry-cf-for-k8s-e61ba64/tests/smoke/assets/test-node-app

Creating app cf-for-k8s-smoke-1-app-73452f418909b043...
Comparing local files to remote cache...
Packaging files to upload...
Uploading files...
 530 B / 530 B [========================================================================================================================================================================================================================================================================================================================================================================================================================================================================================] 100.00% 1s

Waiting for API to complete processing files...

Staging app and tracing logs...
FAILED
Error staging application: Stager error: Kpack build failed. build failure message: 'pods "72f8ffec-de2d-4218-bf9c-c8aa2d2bf34d-build-1-l8k96-build-pod" already exists'.
```

### Expected behaviour

_What was the expected result?_
The tests do not flake.

**Comment by jamespollard8** [comment]
Thanks @mnitchev! We've informed the kpack team about this issue and just messaged them for an update on the [slack thread here](https://cloudfoundry.slack.com/archives/CUWG5TXB5/p1591133945080800?thread_ts=1591123619.080300&cid=CUWG5TXB5)

**Comment by jamespollard8** [comment]
Closing as fixed because we haven't seen this issue quite in a while
