### ISSUE TITLE
`app_registry.repository` configuration parameter is misleading and should be renamed

### ISSUE THREAD

**Issue by emalm** [cloudfoundry/cf-for-k8s#249]
### Summary

The cf-for-k8s configuration values include a parameter named [`app_registry.repository`](https://github.com/cloudfoundry/cf-for-k8s/blob/b63f692f822893e84fedea7ea2b194e8ee1810fd/config/values.yml#L136). This parameter is misleading: kpack creates image repositories starting with this value for each separate app, so it is incorrect to supply an existing repository in an OCI image registry as a value for this parameter. It would be more accurate to call this parameter something like `app_registry.repository_prefix`.

### Reproduction Steps

For example, when using Dockerhub as the app image registry, the [deploy docs](https://github.com/cloudfoundry/cf-for-k8s/blob/b63f692f822893e84fedea7ea2b194e8ee1810fd/docs/deploy.md#option-b---create-the-install-values-by-hand) state that this parameter should have the value `username`, and not `username/repository`. Specifying an existing image repository as this value leads to an error when kpack builds an app image, as it cannot access a repository with the pathway `username/repository/APP-GUID` in Dockerhub:

```
$ cf push catnip
(snip)
Staging app and tracing logs...
   prepare:main.go:83: invalid credentials to build to ematpl/alpine/26312df4-3467-4d77-82b6-16bfaac684c2
Error staging application: Stager error: Kpack build failed. build failure message: ''. err: 'the server could not find the requested resource (get pods 26312df4-3467-4d77-82b6-16bfaac684c2-build-1-n2spr-build-pod)'
```

Similarly, when using Harbor as an app image registry, this parameter should have the value `HARBOR-FQDN/CF-IMAGES-PROJECT`, where `CF-IMAGES-PROJECT` is an existing Harbor project that is intended to contain the app-specific image repositories that kpack creates. In this case, specifying the value `HARBOR-FQDN/CF-IMAGES-PROJECT/EXISTING-REPOSITORY` causes kpack to create new repositories of the name `CF-IMAGES-PROJECT/EXISTING-REPOSITORY/APP-GUID` under that Harbor project, which is confusing, if not an outright failure.

### Expected behavior

I expect the configuration parameter naming schema and corresponding documentation to indicate clearly the true nature of these values so that I can configure them without cognitive dissonance.

**Comment by Birdrock** [comment]
@emalm This proposal is reasonable. We've made the changes on a branch of cf-for-k8s and opened a pull request with capi to update their configuration.

**Comment by Syerram** [comment]
Resolved. The new registry property is called `repository_prefix`
