### ISSUE TITLE
Colocated k8s ingresses registering as cf-for-k8s routing targets?

### ISSUE THREAD

**Issue by aegershman** [cloudfoundry/cf-for-k8s#252]
**Is your feature request related to a problem? Please describe.**
NOTE: I feel I need to read and get a better understanding of [cf-for-k8s-networking here](https://github.com/cloudfoundry/cf-for-k8s/blob/master/config/gateway.lib.yml) and [here](https://github.com/cloudfoundry/cf-k8s-networking/tree/master/doc/no-loadbalancer), but I figure I'll ask in case other folks had immediate thoughts or knowledge (or the same question):

I'd like to know if I can deploy services colocated on the same cf-for-k8s cluster and leverage the same istio ingress routing as the platform is using

In order to access `grafana`/`prometheus`/`alertmanager`/`harbor`, any other service which would otherwise leverage an `ingress`, I'm curious if we can have those ingress targets be registered with the cf-for-k8s routing; e.g., assuming a `system_domain` of `vcap.me`, a separate kubernetes deployment like [`prometheus/grafana`](https://github.com/coreos/prometheus-operator) being able to have an ingress on `grafana.vcap.me`, too.

**Describe the solution you'd like**
Just curious if it's possible to have other deployments besides `cf-for-k8s` leverage an `ingress` via the same istio ingress controller routing that `cf-for-k8s` uses

**Describe alternatives you've considered**
Deploy another ingress controller for non-CF deployments. But then you can't leverage the same shared domain, and it makes it more difficult to use a single ingress in a `kind`/`minikube` env via `vcap.me`/`xip.io`, can't use the same certs generated for the domain, etc.

I tried deploying ingresses with an annotation wiring up the ingress class of `istio` to see if it'd register, but that's a little... not correct 😬 maybe I just haven't dug deep enough into it yet

**Additional context**

[I was inspired by this `cf-for-k8s-metrics-examples` repo](https://github.com/cloudfoundry/cf-for-k8s-metric-examples/blob/master/go-app-with-metrics/manifest.yml) demonstrating annotations passed through to pods created by eirini, and [setup a test of running cf-for-k8s and prometheus/grafana on the same `kind` cluster](https://github.com/aegershman/deployments/blob/master/cf-for-k8s/config/prometheus-operator/values.yml).

The equivalent of what I'm trying to do from BOSH/CF-land is having CF deployed with the routing-release, and then other deployments register themselves as routing targets using route-registrar-- see also, [`prometheus-boshrelease` operator for `enable-cf-route-registrar`](https://github.com/bosh-prometheus/prometheus-boshrelease/blob/master/manifests/operators/enable-cf-route-registrar.yml)

This would have value for running other deployments on the same cluster as cf-for-k8s which could otherwise just use the same `ingress`, e.g. jaeger, zipkin, prometheus/grafana, usage metering, and-- maybe if you're into living a little dangerously, why not-- concourse, tekton, etc.

With all this said, I'll better educate myself on cf-for-k8s-networking

Thanks for everyone's time, thanks for all you all do 👍

**Comment by XanderStrike** [comment]
Hey! This is explicitly not supported, we don't really expect people at the moment to deploy anything other than cf-for-k8s to their clusters.

That being said, you can totally do this by creating a [VirtualService](https://istio.io/latest/docs/reference/config/networking/virtual-service/) that selects the IngressGateway we create. I do it for testing purposes now and then and it works fine. Take a look at the VirtualServices that are created for CF workloads for an example to build off of. You will probably need to deploy your pods/services into the cf-workloads namespace, or if you create a new namespace you'll have to turn on istio sidecar injection for that namespace.

Again, though, this isn't recommended or supported. You're gonna run into problems with future upgrades and we make no guarantees that newer versions of our networking configuration plane will be compatible with your changes.

Good luck!

**Comment by aegershman** [comment]
Thanks for the heads up. I hear you about it not being officially supported at the moment; however, I will say though, if we're talking about ✨visions of the future✨, demonstrations of deploying auxiliary tooling alongside CF in the same cluster, [like prometheus/grafana/zipkin/policy management/etc.](https://github.com/cloudfoundry/cf-for-k8s-metric-examples), shows a little hint of pairing cf with other independent tooling (ostensibly on the same cluster) could be wildly powerful in the long-run. Idk, just wanting to point it out as a background thing, even if it isn't in the cards at the moment. regardless I'll save my blabbing for rfcs and proposals and such 😉 

Thanks for your advice and time, I appreciate it, I'll try it out 👍

**Comment by aegershman** [comment]
last thing since this is a closed issue--

for the record, I see now what you mean about plopping in a virtualservice. I realize I should get more familiar with istio (/ service meshes in general) to get a more in-depth understanding of && advantage on modifying cf-for-k8s. 

in case anyone else stumbles upon this, [here's a quick example as a starting point to hack around](https://istio.io/latest/docs/reference/config/networking/virtual-service/)

```yml
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: grafana-virtual-service
  namespace: prometheus-operator
spec:
  hosts:
    - grafana.vcap.me
  gateways:
    - cf-system/istio-ingressgateway
  http:
    - route:
        - destination:
            host: prometheus-operator-grafana.prometheus-operator.svc.cluster.local
            port:
              number: 80
```

thanks again for your help and advice 👍
