### ISSUE TITLE
Unable to push java/spring and php apps from CATS

### ISSUE THREAD

**Issue by ericpromislow** [cloudfoundry/cf-for-k8s#259]
# Placeholder: Test paketo buildpack sample apps

## Describe the bug

Sample apps that still can't be pushed:
[here](https://cloudfoundry.slack.com/archives/CH9LF6V1P/p1593134377238400)

"""
For e.g. our PHP app has a single file index.php and pushing that doesn't work (some error like cannot find app.php)
"""

First, verify that we can push the sample apps from [paketo](https://github.com/paketo-buildpacks/)

Then figure out what the differences in cats are

**Comment by Syerram** [comment]
Closing this issue because we will be tracking it in a separate doc.
