### ISSUE TITLE
Default-Deny Network Traffic for System Components

### ISSUE THREAD

**Issue by tcdowney** [cloudfoundry/cf-for-k8s#262]
**Is your feature request related to a problem? Please describe.**
We (cf-k8s-networking team) have a story ([#173371423](https://www.pivotaltracker.com/story/show/173371423)) around adding Layer 3 (L3) [`NetworkPolicy`](https://kubernetes.io/docs/concepts/services-networking/network-policies/) to default-deny traffic to/from system components. Components will need to explicitly allow traffic.

This will provide the following benefits:
* Improve the security posture of the platform. Additive allow policies will require conscious effort to enable components to interact with each other.
* These policies can help serve as living documentation around what network interactions are taking place between components. Similar to [these existing docs](https://github.com/pivotal-cf/docs-pcf-security/tree/2.9/networking), they'll show what protocols and ports are in use and where we expect traffic to be coming from.

**Describe the solution you'd like**
We will be adding `NetworkPolicy` _somewhere_ in `cf-for-k8s`. Right now it's kind of scattered all over the place (some lives in [eirini.yml](https://github.com/cloudfoundry/cf-for-k8s/blob/9e8556471b4b34910405423e9f69f941174960ee/config/eirini.yml#L21-L44) for example).

We propose **a central `config/network-policy.yml` file** that contains this configuration for all of the system components in `cf-for-k8`s so that an operator can see what is going to be applied at a glance. 

Alternatively components could manage these `NetworkPolicy` entries themselves and `cf-for-k8s` would just contain the initial "default-deny" policy. However, that feels more difficult to manage overall and poses release coordination issues.

These policies require coordination between various components (`podSelector`s and such need to line up) so having them managed in a central place feels valuable.

**Describe alternatives you've considered**
A good question was raised by @kauana around why not use Layer 7 (or L3 **and** L7) policies (in our case this would be [Istio `AuthorizationPolicy`](https://istio.io/latest/docs/reference/config/security/authorization-policy/#AuthorizationPolicy)) for this? We [discussed this on Slack a bit here](https://cloudfoundry.slack.com/archives/CFX13JK7B/p1593538184408400) and settled on L3 `NetworkPolicy` should be the minimum required amount of security provided. L7 policies can be layered on to provide additional security, but may not be required (or desired) for all components.

Some thoughts we had:

* L3 `NetworkPolicies` provide a good service mesh agnostic baseline level of protection<sup>1</sup>.
* `NetworkPolicies` are easy to manage at a platform level and should be familiar to most Kubernetes operators.
* They don't require deep knowledge of specific interactions between apps. A lot of L7 policies wind up including information on specific HTTP endpoints. See this [cfroutesync policy](https://github.com/cloudfoundry/cf-k8s-networking/blob/d2722461559be5ccb807f8a7dbcb93c333fad48b/config/cfroutesync/cfroutesync.yaml#L88-L119) for example. It only authorizes the metacontroller component to reach the `/sync` endpoint while allowing all to access the `/metrics` endpoint. This kind of policy is valuable _in addition to_ the L3 Network Policy, but require deeper context from the component teams to manage.

_<sup>1</sup> L3 `NetworkPolicy` is not sufficient in all cases, however. Components that relied on mTLS to make authorization decisions in CF for VMs will want to use L7 `AuthorizationPolicies` to provide more granular control. Take the Cloud Controller, for example. It has a set of public APIs that it wants _everyone_ to be able to access and relies on Oauth2 for these endpoints **as well as** a set of private APIs that use mTLS certificates for authz. Cloud Controller will want its L3 `NetworkPolicy` to be very permissive in this case and should use L7 policy to limit access to specific endpoints based on TLS certs._

**Additional context**
We will be submitting a PR as part of [#173371423](https://www.pivotaltracker.com/story/show/173371423) to do this initially for what exists in `cf-for-k8s` today. As components are added in the future they'll need to add `NetworkPolicy` to communicate with their collaborators.

Additionally, while we can infer what needs to talk to what for the initial PR by seeing that the deploy is successful and that smoke tests pass, it's likely that we'll miss some policies. We would appreciate help from the other component teams in this area. I'm hoping to use this issue as something to help coordinate things.

Thanks!
Tim && @cloudfoundry/cf-networking

---

Tagging a couple component teams as well:
@cloudfoundry/cf-loggregator 
@cloudfoundry/cf-capi 

Please let us know about the existing network connectivity between your components and review the PR once it's submitted!

**Comment by tcdowney** [comment]
> We have created an issue in Pivotal Tracker to manage this:
> 
> https://www.pivotaltracker.com/story/show/173594550
> 
> The labels on this github issue will be updated when the story is started.

This Issue is mostly informational. I'd expect it not to be actionable until there is a PR submitted.

**Comment by mcwumbly** [comment]
> These policies can help serve as living documentation around what network interactions are taking place between components. Similar to [these existing docs](https://github.com/pivotal-cf/docs-pcf-security/tree/2.9/networking), they'll show what protocols and ports are in use and where we expect traffic to be coming from

Maintaining those docs is no easy task! I would love to see this happen for this reason alone...

**Comment by loewenstein** [comment]
Is this issue for inbound system component traffic alone and the default deny egress will be handled separately? Asking because of the implications for external databases.

**Comment by shalako** [comment]
Hi Jan, this is for pod East/West within the system namespace.

**Comment by tcdowney** [comment]
@shalako I think to @loewenstein's point the `NetworkPolicies` will end up impacting North/West traffic as well. Adding an `egress` rule permitting some East/West traffic in the system namespace will make it deny all other egress traffic for the pods that the policy applies to. I think may need to explicitly allow some of the system components to egress to [public IPs](https://github.com/cloudfoundry/cf-deployment/blob/2ce048139541c3cafe47475f521111a9c131dacd/cf-deployment.yml#L885-L896). We also may need permissive egress rules for components that talk to external Kubernetes APIs.

I guess is it fair to say that limiting egress in these cases is not in scope though in the implementation we might end up having to explicitly permit it?

We will also have to add policies that go across namespaces since not all of the system components live in `cf-system` (e.g. the database is in `cf-db`, the blobstore is in `cf-blobstore`, etc.), but I don't think this distinction is that important.

**Comment by JamesClonk** [comment]
@tcdowney Is it also planned to include adding a general deny policy for `cf-system` ingress coming from `cf-workloads` (and possibly `cf-workloads-staging`) to not be able to access pods or services in `cf-system` directly, for example via `capi.cf-system.svc` or `uaa.cf-system.svc`, etc.. 
To force apps to have to use the "public" route `https://api.<system-domain>` for example when they want to talk to cloud-controller / the API and not being able to potentially mess with any of the system components.
Maybe have it expanded to deny ingress not just from cf-workloads, but from anything which is not one of the main cf system components namespaces?

**Comment by tcdowney** [comment]
@JamesClonk yeah, that's the goal. That behavior would be equivalent to how it works in CF for BOSH today where I believe you would need to write an [ASG](https://docs.cloudfoundry.org/concepts/asg.html) explicitly allowing apps to reach the Cloud Controller/UAA/etc. VMs.

**Comment by tcdowney** [comment]
Work in progress PR: https://github.com/cloudfoundry/cf-for-k8s/pull/270/files

**Comment by jamespollard8** [comment]
Fixed by #270
