### ISSUE TITLE
External Database: CA cert secret written to wrong namespace

### ISSUE THREAD

**Issue by loewenstein** [cloudfoundry/cf-for-k8s#274]
## Describe the bug
The [Secret in capi-k8s-release/templates/database-ca-cert-secret.yml](https://github.com/cloudfoundry/capi-k8s-release/blob/master/templates/database-ca-cert-secret.yml#L8) is missing a namespace and hence put into the 'default' namespace. It cannot be mounted across namespaces and hence several CAPI Deployments cannot be started.

To fix it, we need to make a change to capi-k8s-release and bump capi-k8s-release in cf-for-k8s.

## To Reproduce*
1. Follow the [external database documentation](https://github.com/cloudfoundry/cf-for-k8s/blob/master/docs/configuration/external-databases.md)

_It's helpful to include snippets of the error response or logs output_

## Expected behavior
cf-for-k8s installs fine and works

**Comment by loewenstein** [comment]
We'll be working on a fix

**Comment by Syerram** [comment]
@loewenstein we have the option of adding an overlay as a stopgap solution till capi fixes the issue. Also, I am curious whether the secret should be owned by cf-for-k8s and not CAPI. The Secret proposal doesn't call out this specific usecase but this similar to ingress gateway, where cf-for-k8s owns the Secret resource and puts in the right namespace.

**Comment by davewalter** [comment]
I can see the fix in the capi-k8s-release templates included in cf-for-k8s: https://github.com/cloudfoundry/cf-for-k8s/blob/3fa14de015688f5fcff20c4d88558069c3da505e/config/capi/_ytt_lib/capi-k8s-release/templates/database-ca-cert-secret.yml#L9
