### ISSUE TITLE
Deployment to kind (aka kubernetes-in-docker)

### ISSUE THREAD

**Issue by julian-hj** [cloudfoundry/cf-for-k8s#29]
### Why
It is super handy for developers to be able to run & test against CF running locally on a laptop.  It will also make our pipelines faster and cheaper if we can spin up clusters directly within Concourse.

#### kind doesn't support LoadBalancers
The istio configuration tries to make a load balancer for ingress.  That piece of the configuration just hangs forever in kapp, because kind can't create it.  To work around that, the load balancer needs to be replaced by a NodePort, and needs to map ports 80 & 443 to predicable allowable 3xxxx port numbers on the worker node.  Those ports in turn need to be mapped back to 80 & 443 in the kind cluster configuration when the cluster is created.  These config files help:

[ingress_for_kind.yml.txt](https://github.com/cloudfoundry/cf-for-k8s/files/4221541/ingress_for_kind.yml.txt)
[kindconfig.yml.txt](https://github.com/cloudfoundry/cf-for-k8s/files/4221542/kindconfig.yml.txt)

#### cfroutesync tries to use the public ingress DNS to talk to UAA and CAPI
In our case, we are using localhost as the ingress.  That won't work for pods running in k8s to reach UAA and CAPI.  Instead those need to use the k8s internal network. This config file patches up cfroutesync's ConfigMap

[routesync_internal_network.yml.txt](https://github.com/cloudfoundry/cf-for-k8s/files/4221543/routesync_internal_network.yml.txt)

### How to get it all running on kind

1) choose a public dns wildcard domain that maps back to 127.0.0.1.  I like `vcap.me` but you can also use `127.0.0.1.nip.io` or any one of a long list of them.
```
./hack/generate-values.sh vcap.me > cf-values.yml
```

2) spin up a kind cluster with the attached config.  This will also pin k8s to 1.15 so that it doesn't choke on the fluentd config:
```
kind create cluster --config=kindconfig.yml
```

3) use `ytt` to generate config with the patches applied
```
ytt -f ./config -f cf-values.yml -f routesync_internal_network.yml.txt -f ingress_for_kind.yml.txt > dump.yml
```

4) Use `kapp` to deploy the whole mess as usual
```
kapp deploy -a cf -f ./dump.yml -y
```

5) you should now be able to target cf and login and do all the normal stuff:
```
cf api api.vcap.me --skip-ssl-validation
cf auth admin `yq -r .cf_admin_password cf-values.yml`
```

I'm happy to pair with y'all if you have any interest in incorporating these changes into cf-for-k8s. LMK.  Note also that the attached files have an annoying .txt extension.  I had to add that to get around GitHub's strangely arbitrary list of acceptable file extensions for attachments.

**Comment by tcdowney** [comment]
Agreed that we need a better local development flow (I bet @zrob would as well 😅) since I think he hacked through yet another way to get it working locally (Docker for Mac in his case).

We have this documented to lay down a daemonset of envoys that listen on nodePort `80`/`443` which is kind of similar to that `ingress_for_kind.yaml` you made.
 
https://github.com/cloudfoundry/cf-k8s-networking/tree/master/doc/no-loadbalancer

Hadn't thought about the `LoadBalancer` service type hanging cause of `kapp`. Just figured it would never provision the external IP. That's a good find.

Talking to Cloud Controller / UAA on internal addresses is something we should do by default anyway in my opinion... our config talking to them externally is a holdover from the days they were still BOSH deployed in our environments.

**Comment by jkbschmid** [comment]
> Talking to Cloud Controller / UAA on internal addresses is something we should do by default anyway in my opinion... our config talking to them externally is a holdover from the days they were still BOSH deployed in our environments.

Agree. This would also solve an issue preventing us from using externally-valid certs at the ingress.

**Comment by kramerul** [comment]
We ran into the same issue when we tried to use an official signed certificate. Therefore, we provided a PR #32 which will fix the stuff in `routesync_internal_network.yml.txt`

**Comment by jenspinney** [comment]
The release integration team is actively exploring approaches for enabling local development. Extra details and progress can be found in this story: https://www.pivotaltracker.com/story/show/171321652

**Comment by julian-hj** [comment]
I've posted a little deploy script & README here for folks who'd like to get up and running on a local cluster until it's officially supported in cf-for-k8s:

https://github.com/cloudfoundry/smb-volume-k8s-local-cluster/tree/master/cf-on-kind

If you have 8 cores, 8 GB ram, and 8 minutes, you could have a running cf-for-k8s!

**Comment by davewalter** [comment]
Thanks again for filing this with such clear and easy to follow steps @julian-hj.

Now that we have [docs](https://github.com/cloudfoundry/cf-for-k8s/blob/develop/docs/deploy-local.md) in this repo to support the local deployment workflow on kind (using the above instructions) and minikube (using minikube tunnel), I am going to close this issue out.

**Comment by julian-hj** [comment]
I just tested this locally, and can confirm that it is working nicely.  Thanks for pulling it in!
