### ISSUE TITLE
hacks/generate-values.sh leaves carriage returns in the certs on mac

### ISSUE THREAD

**Issue by pusherofbrooms** [cloudfoundry/cf-for-k8s#312]
## Describe the bug
The `hacks/generate-values.sh` script leaves the carriage returns (looks like ^M in emacs or vi) in place in the generated certs when run on my mac.

## To Reproduce*
Run `hacks/generate-values.sh` on a mac and inspect the certs in the `cf-values.yml` output

## Expected behavior
Carriage returns should be removed as well.

## Additional context
I suggest replacing all occurrences of `tr -d '\n'` with `tr -d '\r\n'` in the hack/generate-values.sh script.

### cf-for-k8s SHA 
Not sure what this means. I'm using commit 5016da8f1ab0b90d1e626109897801301f01b4d1 , but this bug seems to exist in the 0.4.0 release as well.

### Deploy instructions
I don't get as far as a deploy because ytt errors due to the carriage returns.
```
ytt -f config -f config-optional/remove-resource-requirements.yml -f config-optional/remove-ingressgateway-service.yml -f config-optional/add-metrics-server-components.yml -f config-optional/patch-metrics-server.yml -f ${TMP_DIR}/cf-values.yml > ${TMP_DIR}/cf-for-k8s-rendered.yml
kapp deploy -a cf -f ${TMP_DIR}/cf-for-k8s-rendered.yml -y
```

### Cluster information
`kind create cluster --config=./deploy/kind/cluster.yml`
which creates a v1.18.2 cluster

### CLI versions
```
 $ ytt --version
ytt version 0.28.0
 $ kapp --version
kapp version 0.30.0

Succeeded
 $ kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.5", GitCommit:"e6503f8d8f769ace2f338794c914a96fc335df0f", GitTreeState:"clean", BuildDate:"2020-06-27T00:36:48Z", GoVersion:"go1.14.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-30T20:19:45Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
 $ cf version
cf version 6.51.0+2acd15650.2020-04-07
```

**Comment by davewalter** [comment]
Hi @pusherofbrooms,

Thanks for reporting this. I am a bit confused as we develop on Macs as a team, and I do not recall ever seeing `^M` at the end of a certificate when editing a values.yml file generated by the script. I just checked one I created yesterday with both neovim (NVIM v0.4.3, my default text editor of choice) and emacs (GNU Emacs 26.3) on Catalina 10.15.6 and I didn't see the carriage return characters, and I also didn't see any errors when running ytt with that file. I wonder if it has something to do with a specific setup on your machine. 🤔 Would it be possible for you to paste in the error that you are getting?

That having been said, I don't see any harm in updating the `tr` calls to include removing the carriage returns. I think we would also need to run the UAA JWT signing key through `tr -d '\r'` to eliminate trailing carriage returns at the end of each line of that certificate, as it is not base64 encoded. Please try that out and let us know if it works. We would be happy to accept a pull-request with these changes.

Regards,
Dave

**Comment by pusherofbrooms** [comment]
I dug into the tools used in those tr pipelines. It appears that I had installed `base64` from homebrew, which first in the path ahead of the builtin base64. When I removed the homebrew base64, `hack/generate-values.sh` functioned as it should.

Closing this issue seems appropriate since I'm probably an odd corner case.
