### ISSUE TITLE
cf push fails with "Error staging application: Staging time expired: staging failed"

### ISSUE THREAD

**Issue by mcwumbly** [cloudfoundry/cf-for-k8s#324]
## Describe the bug

When running `cf push` with a small node app this morning on our (@cloudfoundry/cf-networking ) long-running cf-for-k8s environment it failed sometimes with the error message

```
Error staging application: Staging time expired: staging failed
```

@christianang helped us this morning and thinks the root cause is likely different from the issue originally reported in https://github.com/cloudfoundry/cf-for-k8s/issues/140, so we are reporting it separately

## To Reproduce*
Not sure... wait a long time and then try to `cf push` maybe?

## Expected behavior
`cf push` succeeds

## Additional context

Here's what we did, in case it's helpful for others who run into this until it's fixed, and/or for those looking into this issue.

We poked around a bit in the following places first:
```
# check what's up in the staging namespace
#... noticed there were no new jobs... everything was from > 10d ago
kubectl get po -n cf-workloads-staging
```

```
# looked at the logs for `kpack-watcher`
# saw no logs newer than > 10 days ago
kubectl logs cf-api-kpack-watcher-7dcc48b9b6-v8clq -n cf-system -c cf-api-kpack-watcher
```

```
# delete kpack watcher to force it to restart
kubectl delete pod/cf-api-kpack-watcher-7dcc48b9b6-v8clq -n cf-system
```

our push was still hanging...

```
# try pushing again, got error:
cf push
...
Staging app and tracing logs...
The app is invalid: VCAP::CloudController::BuildCreate::StagingInProgress
FAILED
```

```
# delete app, push again... now we're OK
cf delete -f ourapp
cf push
```

### cf-for-k8s SHA 
https://github.com/cloudfoundry/cf-for-k8s/tree/v0.4.0

### Deploy instructions
...

### Cluster information
GKE

### CLI versions
_paste output of the following commands_

1. `ytt --version`: `ytt version 0.28.0`
2. `kapp --version`: `kapp version 0.31.0`
4. `cf version`: `cf version 6.51.0+2acd15650.2020-04-07`
3. `kubectl version`: 

```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"clean", BuildDate:"2020-07-15T16:58:53Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.9-gke.6", GitCommit:"14bc8ad5f8c245f1240a8e4eab128c4d51bfeffe", GitTreeState:"clean", BuildDate:"2020-05-30T02:07:03Z", GoVersion:"go1.13.9b4", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by davewalter** [comment]
Hi @mcwumbly,

Thanks for reporting this. Do you happen to know what version/sha of cf-for-k8s you were running when the app was originally pushed?

There was a [change](https://github.com/cloudfoundry/cf-for-k8s/commit/82f2893a4ba050d2a7c458eb7d5959e263e66767) that was introduced on June 24th where CAPI switched from an autodetect-builder that was included in their templates to a default builder included in the cf-for-k8s templates. This was a breaking change for apps that had been pushed to the platform prior to upgrading cf-for-k8s as CAPI cached the builder used to originally push the app and attempted to re-use it when the app was re-pushed. The only workaround was to delete the app and re-push it as a fresh app. If I recall correctly, the error was in the logs for the cf-api-server as no request was made to kpack. Does that fit with the timeline for your long-lived environment?

Regards,
Dave

**Comment by mcwumbly** [comment]
Prior to attempting to push the app on July 29th, I see the last time it was pushed was on July 9th, per:
```
$ cf curl "/v2/events?order-by=timestamp&order-by=id&order-direction=asc&page=1&results-per-page=100" | jq '.resources[].entity | select(.actee_name=="slackbot")' | grep timestamp
  "timestamp": "2020-07-07T01:05:34Z",
  "timestamp": "2020-07-08T20:24:59Z",
  "timestamp": "2020-07-08T20:24:59Z",
  "timestamp": "2020-07-08T20:25:00Z",
  "timestamp": "2020-07-08T20:25:01Z",
  "timestamp": "2020-07-09T01:37:40Z",
```

Given that https://github.com/cloudfoundry/cf-for-k8s/tree/v0.4.0 was updated on July 26th, it must have been deployed after the change  you mentioned.

Then the question (as you asked) is, what version was deployed on July 9th?

I'm not quite sure how to do _that_ archaeology at this time on a Friday afternoon.  @christianang any thoughts on how to answer that question?

**Comment by christianang** [comment]
Not sure if there is a good way to get the exact sha we had deployed on July 9th. However, there was only one other deployment we did before July 26th (the initial deployment), and that occurred 60 days ago on June 1st. Considering the commit happened on June 24th I imagine we could be hitting the scenario @davewalter is mentioning.

**Comment by jamespollard8** [comment]
Given that we're not yet supporting upgrades, we're going to close this issue.

Thanks @christianang for getting back to us.

As a side note, we have this on our radar "Not sure if there is a good way to get the exact sha we had deployed on July 9th."
