### ISSUE TITLE
log-cache has up to 7 restarts during installation

### ISSUE THREAD

**Issue by kramerul** [cloudfoundry/cf-for-k8s#329]
## Describe the bug

log-cache needs up to 7 restarts during installation, which will also lead to an error in kapp

```
Finished unsuccessfully (Deployment is not progressing: ProgressDeadlineExceeded (message: ReplicaSet "log-cache-d5dfc9c98" has timed out progressing.))
```

This is also increasing the total installation time.

## To Reproduce*
1. Install cf-for-k8s using kapp

## Expected behavior

`log-cache` doesn't fail at all.

### cf-for-k8s SHA 

55e5e474ce61d985f03bdc3b22511d1cf23bf71c

### Deploy instructions

We are not able to provide all config files. This should also happen in every standard installation.

### Cluster information

* GCP cluster

### CLI versions

1. `ytt --version`: 0.28.0
2. `kapp --version`: 0.30.0
3. `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"clean", BuildDate:"2020-07-16T00:04:31Z", GoVersion:"go1.14.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.10", GitCommit:"f3add640dbcd4f3c33a7749f38baaac0b3fe810d", GitTreeState:"clean", BuildDate:"2020-05-20T13:51:56Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```
4. `cf version`: `cf version 6.51.0+2acd15650.2020-04-07`

**Comment by jamespollard8** [comment]
The log-cache team removed the dependency on UAA and now starts up more smoothly.
