### ISSUE TITLE
Ability to configure a private registry

### ISSUE THREAD

**Issue by lisamburns** [cloudfoundry/cf-for-k8s#338]
**Summary**
This feature enables users to configure a private registry that is not available externally.

**Intended Outcome**
This feature will allow users to use a private registry on a private network

**What alternatives were considered**
Users can use public docker registries

**How will it work**
Need exploration

**Comment by paulcwarren** [comment]
Support for [this](https://github.com/cloudfoundry/cf-for-k8s/blob/develop/docs/platform_operators/system-registry-management.md) was added just prior to 1.0
