### ISSUE TITLE
cf push with buildpack choice does not work

### ISSUE THREAD

**Issue by Syerram** [cloudfoundry/cf-for-k8s#340]
## Expected behavior
- When I push app `cf push -b <buildpack-name>`, I expect CF to build an app with an existing buildpack name

## Actual behavior
- When I run `cf push -b <buildpack-name>`, it fails since there are no buildpacks currently listed

## Workaround
None

## Context
This is a known issue and will be tackled post 1.X release. The issue will be updated once we have a timeline.

**Comment by acosta11** [comment]
Update: as of https://github.com/cloudfoundry/capi-k8s-release/releases/tag/v0.3.0 , we now have the ability to specify a buildpack for cf push if it has already been configured for use in the kpack builder and store. But the release notes do not indicate the ability to specify stack at cf push time, so leaving this issue open.

**Comment by Syerram** [comment]
Release as part of v0.6.0
