### ISSUE TITLE
Platform engineers want to deploy cf-for-k8s on EKS 

### ISSUE THREAD

**Issue by Syerram** [cloudfoundry/cf-for-k8s#345]
## Summary
This feature enables deployment of cf-for-k8s on AWS cloud infrastructure (especially EKS k8s distribution). There is a big population of users who use AWS but struggle to install cf-for-k8s due to some nuances when installing on AWS EKS distribution. We want to remove the friction by adding the necessary configuration to support EKS and ECR (Amazon registry), adding appropriate documentation, and validate in CI so AWS users can successfully install cf-for-k8s on EKS.

## Evidence
- Users failed to install cf-for-k8s on EKS - recent threads [slack thread 1](https://cloudfoundry.slack.com/archives/CH9LF6V1P/p1596466057163100), [slack thread 2](https://cloudfoundry.slack.com/archives/CH9LF6V1P/p1581346419064400). 
- Questions from attendees at CF foundation and OSS

## Use cases
1. Fresh deploy cf-for-k8s to EKS using ECR as the registry
2. Upgrade cf-for-k8s to EKS using ECR as the registry

## Intended Outcome
AKS is in the top 3 Cloud Kubernetes distributions. Expanding to AWS will increase our reach to new users and further bolster the CF community. 

## What alternatives were considered
Currently, testing on GKE and AKS but they aren't the same as EKS.

## How will it work
[Need exploration]

**Comment by paulcwarren** [comment]
We recently added EKS to our [pipeline](https://release-integration.ci.cf-app.com/teams/main/pipelines/cf-for-k8s-iaas-tests) so this is now being tested on a regular basis.
