### ISSUE TITLE
Request: air-gapped environment image relocation guide

### ISSUE THREAD

**Issue by acosta11** [cloudfoundry/cf-for-k8s#365]
**Is your feature request related to a problem? Please describe.**
As a user of cf-for-k8s with heightened security and availability requirements on my image registry, I would like to control the location of the images used by cf-for-k8s. Currently, image locations are not fully configurable in the cf-for-k8s data values interface.

**Describe the solution you'd like**
I would like a quick-start guide for configuring references to all of the artifacts required to deploy cf-for-k8s. This would enable the creation of an air-gapped environment alongside networking policies.

Similarly, we would like ongoing support/validation of this guide from the cf-for-k8s maintainers.

**Describe alternatives you've considered**
We have a workaround for managing image references with the `kbld` tool from [this slack conversation](https://cloudfoundry.slack.com/archives/CH9LF6V1P/p1595953719061300).

**Additional context**
While `kbld` technically solves the image reference problem at the moment, it requires some manual toil of managing configuration files that point to all of the images that require relocation. The configuration of those images may change in the absence of process/validation from the maintainers of cf-for-k8s.

**Comment by JamesClonk** [comment]
Also, will there be `offline` buildpacks available like in CF-for-BOSH? Those are a must have for an air-gapped/offline environment too.
