### ISSUE TITLE
YTT should validate my data values before it installs cf-for-k8s

### ISSUE THREAD

**Issue by Syerram** [cloudfoundry/cf-for-k8s#398]
**Is your feature request related to a problem? Please describe.**
I installed cf-for-k8s without adding `app_registry` and yet it deployed successfully but failed on the core cf push workflow.

**Describe the solution you'd like**
cf-for-k8s should validate my data values to ensure I have all the required values set and also the values are of the correct data type and form

**Describe alternatives you've considered**
Inspect manually against the main config file in the repository. This is an error prone process since it is easy to forget.

**Additional context**
cf-for-k8s is working towards YTT schema that will enforce some of the above rules.

**Comment by jamespollard8** [comment]
The changes from https://github.com/cloudfoundry/cf-for-k8s/pull/524 fix this issue, implementing ytt checks for required data values.

```
$ ytt -f config -f <values-file-missing-app_registry>
ytt: Error:
- assert.fail: fail: The following required data.values parameters are missing: ["app_registry.hostname", "app_registry.password", "app_registry.repository_prefix", "app_registry.username"]
    in <toplevel>
      check-required-arguments.yml:8 | require_parameter_check: #@ assert.fail("The following required data.values parameters are missing: %s" % (missing_parameters,))
```
