### ISSUE TITLE
Platform engineers can install cf-for-k8s on their local machine without needing to configure any data values

### ISSUE THREAD

**Issue by Syerram** [cloudfoundry/cf-for-k8s#419]
## Summary
cf-for-k8s is in it's early stage of the product cycle. Users are curious to try out the project before they could consider for production use cases. We want the local install as the out-of-box experience for cf-for-k8s. To accomplish this capability, the default configuration will be optimized to install on a local machine with a minimal footprint.

For now, we intend to support Kind and Minikube.

### Default values
The following table illustrates the default configuration for the main config `config/values/00-values.yml`.

| Config | Default value | Details | 
| ----------- | ------------- |--------- |
| `add_metrics_server_components` | `true` | `kind` requires metrics server. `Minikube` has add on but we can just use this flag to add metrics to minikube as well| 
| `enable_automount_service_account_token` | `true` | | 
| `enable_load_balancer` | `false`| Loadbalancer is not required for local install and hence the default install for gateway will be node-port. We want remove this completely in the future and instead expect Platform engineers to BYO load balancer | 
| `metrics_server_prefer_internal_kubelet_address` | `true` | |
| `remove_resource_requirements` | `true` |  |
| `use_first_party_jwt_tokens` | `true` | |

### First install - on Kind
**Given** that I ran `hack/generate-values.sh -d vcap.me -g <gcr.json> ` 
**When** I generate `ytt` and run `kapp` to install cf-for-k8s on kind
**Then** I am able to connect to the local install via `cf api api.vcap.me --skip-ssl-validation`
&nbsp;&nbsp;**And** I am successfully able to push cf apps

### With a predefined local values YML
**Given** that I have `local-values.yml`
**When** I update the registry setting with a OCI compliant registry
**And** I generate `ytt` and run `kapp` to install cf-for-k8s on kind
**Then** I am able to connect to the local install via `cf api api.vcap.me --skip-ssl-validation`
&nbsp;&nbsp;**And** I am successfully able to push cf apps

### Documentation - Local
- Update documentation to remove the instructions to set for local properties

### Documentation - IaaS Custer
- Add documentation to set for a cluster install

[1] The current documentation in `docs/deploy-local.md` becomes the primary doc with detailed steps copied over from today's `deploy.md` doc.

## Notes
- `hack/generate-values.sh` should use the default domain values `vcap.me` if none is passed. The documentation should also be updated to remove the domain name requirement.
- RelInt will need to update upgrade CI because this will definitely break the long running environment.

**Comment by paulcwarren** [comment]
After discussion we decided that we would leave the defaults as they are.  

We have created a [getting started](https://github.com/cloudfoundry/cf-for-k8s/blob/master/docs/getting-started-tutorial.md) tutorial (that will land on the cf-for-k8s.io site) soon that works around the fact that these aren't set appropriately for a kind/minikube installation by having the user append the settings to the end of their cf values file.   It's a simple copy paste from the tutorial to their shell so hopefully this will suffice.
