### ISSUE TITLE
Re-deploying cf-for-k8s with different credentials fails

### ISSUE THREAD

**Issue by jenspinney** [cloudfoundry/cf-for-k8s#45]
## Summary
If an operator changes the credentials used by cf-for-k8s (e.g., the certs, signing keys, passwords, etc. documented in [sample-cf-values.yml](https://github.com/cloudfoundry/cf-for-k8s/blob/2a62a32adb6902c267b6fff123cda5e48c25ca62/sample-cf-install-values.yml) or generated by [hack/generate-values.sh](https://github.com/cloudfoundry/cf-for-k8s/blob/2a62a32adb6902c267b6fff123cda5e48c25ca62/hack/generate-values.sh)), and then attempts to re-run the `bin/install-cf.sh` script with no other changes, cf-for-k8s will not start up correctly.

## Repro Steps
1. `hack/generate-values.sh put-domain-here > /tmp/values.yml`
1. `bin/install-cf.sh /tmp/values.yml`
1. Observe that cf-for-k8s has successfully deployed.
1. `rm /tmp/put-domain-here/cf-vars.yaml`
1. `hack/generate-values.sh put-domain-here > /tmp/values.yml`
1. `bin/install-cf.sh /tmp/values.yml`
1. Observe that cf-for-k8s fails to deploy:
```
3:49:13PM: fail: reconcile deployment/capi-api-server (apps/v1) namespace: cf-system

kapp: Error: waiting on reconcile deployment/capi-api-server (apps/v1) namespace: cf-system: finished unsuccessfully (Deployment is not
 progressing: ProgressDeadlineExceeded (message: ReplicaSet "capi-api-server-7fb6cbdb8c" has timed out progressing.))
```

## Context
The credentials and other configuration values used by the components of cf-for-k8s are stored in ConfigMap and Secret resources in Kubernetes. If the values of a ConfigMap or Secret are updated, Kubernetes will not automatically restart pods that have those resources mounted. That means that the new values are sitting in Secrets and ConfigMaps but the pods that reference those values have stale information.

Since we are deploying cf-for-k8s with the `kapp` tool, we can solve this by setting the [`versioned` annotation](https://github.com/k14s/kapp/blob/master/docs/diff.md#versioned-resources) on the various ConfigMap and Secret resources of the cf-for-k8s components.

The [Cloud Controller ConfigMap](https://github.com/cloudfoundry/capi-k8s-release/blob/332c231e9a8eb039b748a57d445e785e2d0c6b59/templates/ccng-configmap.yml#L11) is one of the only such resources that is triggering the restart of the pods that use it. During this restart, the Cloud Controller cannot communicate with other components (such as UAA) that did not restart when their secrets changed.

**Comment by acosta11** [comment]
Update: we've scoped this track of work out into an epic which is viewable in Tracker: https://www.pivotaltracker.com/epic/show/4518917

We've gotten config and credential rotation implemented at the Kubernetes resources layer, but need to resolve limitations of the images we're running not supporting declarative rotation in some cases. (See the Postgres story in that epic for an example)

**Comment by paulcwarren** [comment]
This was fixed a while ago.  We have a pipeline job that tests credential rotation.  There are a few exceptions but they are tracked in a known-issue.
