### ISSUE TITLE
Input values for certificates should have a consistent format

### ISSUE THREAD

**Issue by julian-hj** [cloudfoundry/cf-for-k8s#460]
**Is your feature request related to a problem? Please describe.**
Some user provided certificates are base64 encoded, such as the ingress certs. Others are not and we base64 encode them later. This is confusing to users.

**Describe the solution you'd like**

It would be better if we could make the interface we provide to the operator consistent--either all encoded, or all not encoded.

### A/C
When I follow directions to add certificates to my configuration input
Then I can use the same format for all of my certificates

**Comment by emalm** [comment]
I'd advocate for PEM-encoded, but not base64-encoded, for any certificate or RSA private key input values. Platform engineers typically receive PEM-encoded representations of these values and should not have to bother with the extra step of base64-encoding these values when either the YTT templates or the K8s API itself can do it for them. It's also harder to identify a formatting or omission error in a single line that is thousands of characters long than it is in a PEM-encoded block of text.

**Comment by davewalter** [comment]
Fixed in #482.
