### ISSUE TITLE
CF logs command does not return app logs

### ISSUE THREAD

**Issue by jenspinney** [cloudfoundry/cf-for-k8s#47]
## Summary
In cf-for-k8s, we are using log-cache instead of traffic controller for retrieving app logs. Because the CF CLI does not yet have native support for communicating with log-cache, we need to use the log-cache CLI plugin (aka `cf tail`).

## Repro Steps
1. I have deployed an app called `my-app` to cf-for-k8s.
1. `cf logs my-app` returns a timeout error:
```
> cf logs myapp
Retrieving logs for app myapp in org o / space s as admin...

Timeout trying to connect to NOAA
FAILED
```

## Context
The CF CLI team has been working to add built-in log-cache support via the `cf logs` command. We're hoping this functionality may be available as soon as [v6.50.0](https://www.pivotaltracker.com/story/show/170566400).

**Comment by davewalter** [comment]
Even with v6.50.0 of the CF CLI, this is still not working. The current error is:
```console
> cf logs test-app
Retrieving logs for app test-app in org test-org / space test-space as admin...

Failed to retrieve logs from Log Cache: Get /api/v1/info: unsupported protocol scheme ""
FAILED
```

**Comment by zankich** [comment]
I believe this patch should fix it https://github.com/cloudfoundry/capi-k8s-release/commit/ef6f6ab66b2f0a13498301b30dd28b136dadd1e5

**Comment by zankich** [comment]
I was able to view logs by manually adding `https://` to the `log_cache` URL at this line https://github.com/cloudfoundry/cf-for-k8s/blob/6df235e471906de7e09b8f6aa576ea6206d67432/config/_ytt_lib/github.com/cloudfoundry/capi-k8s-release/templates/ccng-config.lib.yml#L123

There were no errors during `cf push` or `cf logs`
```
$ cf push test-node-app -p docs/example-app
...
Creating app test-node-app...
Mapping routes...
Comparing local files to remote cache...
Packaging files to upload...
Uploading files...
 498 B / 498 B [=======================================================================================================================================================] 100.00% 1s

Waiting for API to complete processing files...

Staging app and tracing logs...

Waiting for app to start...

name:                test-node-app
requested state:     started
isolation segment:   placeholder
routes:              test-node-app.cf4k8s.kwikemart.steamedhams.us
last uploaded:       Wed 18 Mar 15:36:25 PDT 2020
stack:
buildpacks:

type:           web
instances:      1/1
memory usage:   1024M
     state     since                  cpu    memory    disk      details
#0   running   2020-03-18T22:36:50Z   0.0%   0 of 1G   0 of 1G
```

```
$ cf logs test-node-app --recent
Retrieving logs for app test-node-app in org test-org / space test-space as admin...

   2020-03-18T15:35:34.47-0700 [/5e84c2dc-2f25-4405-bf44-ecbc84f7706a] OUT prepare:fetch.go:80: Successfully downloaded cf-blobstore-minio.cf-blobstore.svc.cluster.local:9000/cc-packages/b6/f8/b6f8052c-045c-4fee-b3d8-5618db135a85 in path "/workspace"
   2020-03-18T15:36:00.15-0700 [/5e84c2dc-2f25-4405-bf44-ecbc84f7706a] OUT org.cloudfoundry.node-engine 0.0.158
   2020-03-18T15:36:00.15-0700 [/5e84c2dc-2f25-4405-bf44-ecbc84f7706a] OUT org.cloudfoundry.npm         0.1.3
...
```

**Comment by Syerram** [comment]
@jenspinney Closing this issue since `cf logs` is currently working.
