### ISSUE TITLE
Switch from paketo-community Ruby Buildpack to paketo-buildpacks Ruby Buildpack

### ISSUE THREAD

**Issue by kvedurmu** [cloudfoundry/cf-for-k8s#486]
**Is your feature request related to a problem? Please describe.**
Hi from the Paketo team! We've [recently promoted](https://github.com/paketo-buildpacks/rfcs/blob/master/accepted/0005-ruby-promotion.md) the Ruby Buildpack from a community buildpack to an official Paketo Buildpack. 

As a part of this change, the buildpack ID has been updated from `paketo-community/ruby` to `paketo-buildpacks/ruby` and buildpackage artifacts will get published to `gcr.io/paketo-buildpacks/ruby`

**Describe the solution you'd like**
Please start consuming the latest Ruby Buildpack with ID `paketo-buildpacks/ruby`. The existing location (`gcr.io/paketo-community/ruby`) will continue to work, but you will need use `gcr.io/paketo-buildpacks/ruby` in order to continue receiving buildpack releases

**Comment by kvedurmu** [comment]
@paulcwarren I think we can close this? I see this on the latest version of CF for K8s

**Comment by paulcwarren** [comment]
Delivered in 1.0
