### ISSUE TITLE
Extend UAA login with external provider

### ISSUE THREAD

**Issue by bonzofenix** [cloudfoundry/cf-for-k8s#539]
I want  to configure google OAuth provider on UAA/login component. I can not find a way to extend this with ytt. Currently, trying to extend this entry: https://github.com/cloudfoundry/cf-for-k8s/blob/develop/config/uaa/uaa.yml#L217.

This is a gist of the path that I am trying to apply: https://gist.github.com/bonzofenix/4df54af4eb7e9660eeeae41bfa21064f

The output is a string and not a map that I can overlay to merge the configs I need for the login component.

I get the following error when I try to apply this patch:

```
ytt: Error: Overlaying (in following order: 2-fix-null-annotations.yml, capi/staging-ns-label.yml, eirini/eirini.yml, fix-db-startup-order.yml, istio/add-istio-injection.yml, istio/external-routing.yml, istio/istio-kapp-ordering.yml, istio/label-istio-ns.yml, istio/remove-hpas-and-scale-istiod.yml, kapp-ordering.yml, kpack/kapp-order.yml, kpack/kpack-ns-label.yml, kpack/kpack.yml, minio/minio.yml, networking/network-policies.yaml, postgres/postgres.yml, prioritize-daemonsets.yml, uaa/uaa.yml, workloads-namespace.yml, z-kapp-versioned-creds.yml, enable-google-provider.yml):
  Document on line enable-google-provider.yml:4:
    Map item (key 'data') on line enable-google-provider.yml:6:
      Map item (key 'uaa.yml') on line enable-google-provider.yml:7:
        Expected map, but was string
```

Is there a workaround for this?

**Comment by cppforlife** [comment]
note that uaa.yml is actually a string, so you cannot directly overlay into it. https://gist.github.com/cppforlife/34c0284d1de26f9324b475bdcdb10010 shows how to use overlay/replace to decode uaa.yml string into yaml structure, use overlay.apply on top of it and finally encode back to yaml.

**Comment by bonzofenix** [comment]
@cppforlife thank you so much for the workaround! I will go ahead and close this issue as this solves the problem of patching uaa configurations.
