### ISSUE TITLE
Getting Started Doc admin login command not working

### ISSUE THREAD

**Issue by jimbasler-pivotal** [cloudfoundry/cf-for-k8s#546]
The Getting Started doc provides this command to login to cf as admin:
cf auth admin `cat ${TMP_DIR}/cf-values.yml | yq -r .cf_admin_password`

With the recent version of yq this does not work. I was able to make it work by using this command:
cf auth admin `yq read ${TMP_DIR}/cf-values.yml 'cf_admin_password'`

**Comment by acosta11** [comment]
Hi @jimbasler-pivotal ,

Thanks for bringing this issue to our attention. It looks like the command included in the getting start doc is using syntax from a different implementation of yq (python based) https://github.com/kislyuk/yq.

Given the getting started guide itself points to the implementation of yq at https://github.com/mikefarah/yq with the `yq read` syntax you used, we'll go ahead and update the command.

Thanks,
Andrew and @reneighbor
