### ISSUE TITLE
Exposing optional configuration for CF API's S3 blobstore

### ISSUE THREAD

**Issue by jspawar** [cloudfoundry/cf-for-k8s#548]
**Is your feature request related to a problem? Please describe.**
As a platform engineer I currently cannot configure optional settings for the S3 blobstore backing the CF API's resource pool (the blobs which back resource caching). This includes configuring desirable options such as enabling support for encryption-at-rest for the backing S3 blobstore.

**Describe the solution you'd like**
CAKE team recently merged in some changes to accommodate this; however, we were wondering how we should expose this optional configuration to the platform engineers. In the PR related to these changes we laid out two possible options for how to expose this config to platform engineers: https://github.com/cloudfoundry/capi-k8s-release/pull/93

Will paste here as well:

---

1. Add changes to cf-for-k8s to expose that configuration in their install values file and provide a modified values file like so:

    ```diff
    #@data/values
    ---
    system_domain: "jwal.k8s.capi.land"
    cf_admin_password: ...

    blobstore:
      secret_access_key: ...
    +   #@overlay/match-child-defaults missing_ok=True
    +   fog_aws_storage_options:
    +     encryption: "AES256"

    cf_db:
      admin_password: ...
    ```

    Such changes would probably look something like this: https://github.com/cloudfoundry/cf-for-k8s/commit/1038e79c1776ab50aeb6d0852c83936037f696a4 and is what we normally have been doing for similar changes (albeit somewhat a painful process as we've discussed/observed)

1. Make no changes to cf-for-k8s and require that operators supply an additional data values file when deploying CF like so:

    ```yaml
    #@library/ref "@capi-k8s-release"
    #@data/values after_library_module=True
    ---
    blobstore:
      #@overlay/match-child-defaults missing_ok=True
      fog_aws_storage_options:
        encryption: "AES256"
    ```

    and deploy with that additional values file: `kapp deploy -a cf -f <(ytt -f config/ -f install-values.yml -f that-additional-data-values-file.yml)`

**Describe alternatives you've considered**
Can't think of any more, but obviously would welcome any

**Additional context**
What's important to note and might not be obvious from our changes or the examples above is that the `blobstore.fog_aws_storage_options` is intentionally an open-ended config. That is, it would be preferable to just accept any generic hash as its value similar to the analogous property in the BOSH release: https://github.com/cloudfoundry/capi-release/blob/4615d548544ed45332ac2ca8c9346d244cdefbc3/jobs/cloud_controller_ng/spec#L480-L482

Besides continuing to support a configuration interface we understand for this particular piece of our configuration, this also mitigates a lot of constant enumeration and maintenance of options that can be supplied to any/every [S3] blobstore we integrate with. For example, prevents us from having to deal with introduction of new options or changes to existing options

**Comment by jamespollard8** [comment]
Thanks @jspawar, at this point we're trying to hold a firm line on **not including** such widely scoped configuration options explicitly in cf-for-k8s. How'd you feel about adding a helpful doc about this configuration to `docs/platform_operators`, and maybe including an example overlay code snippet within that doc?

**Comment by Birdrock** [comment]
@jspawar Do you remember where this ended up?

cc @jamespollard8

**Comment by paulcwarren** [comment]
Personally, I like option #2 as it places the configuration for the component with the component.  I also think this is a good, flexible long term, approach for an open source product.  BUT it needs first-class support to make it effective and we have no infrastructure to support this approach atm so it would end up being not particularly discoverable by the user and probably confusing.  Once ytt schema arrives and we can generate config docs from all of the components and collect them all together then I think this approach becomes viable (and also scales well across distributed teams).

In lieu of all of that though atm we are using the 80/20 rule...if 80% of the users would want to do this thing then let's pull it up into the cf-for-k8s config; i.e. option 1.  Otherwise, let's do option #2 and manually document it.  (At time of writing we haven't had any option #2's.)

**Comment by jamespollard8** [comment]
We're not prioritizing this issue at this time but when we do, we're thinking option number 2 sounds good and that we could provide an example overlay in our documentation to help users who want to configure these optional blobstore settings.
