### ISSUE TITLE
Accessing cf api endpoint

### ISSUE THREAD

**Issue by arungskumar** [cloudfoundry/cf-for-k8s#551]
Hi Team,
Could you please help me to resolve below issue, that I get when accessing api endpoint of the successfully deployed cf on an aks cluster.

`$ cf api --skip-ssl-validation https://api.cfonaks.azurestack.external                                                                                                                

Setting api endpoint to https://api.cfonaks.azurestack.external...
Request error: Get https://api.cfonaks.azurestack.external/v2/info: dial tcp: lookup api.cfonaks.azurestack.external: no such host
TIP: If you are behind a firewall and require an HTTP proxy, verify the https_proxy environment variable is correctly set. Else, check your network connection.
FAILED`

I am deploying cf on k8s for the first time, not sure if I am missing something here.
Thanks.

Regards,
Arun

**Comment by arungskumar** [comment]
Azure CNI plugin has been configured in the cluster.
[Archive.zip](https://github.com/cloudfoundry/cf-for-k8s/files/5436269/Archive.zip)
Include aks config and cf config files, that were used to build.

**Comment by ericpromislow** [comment]
hi @arungskumar 

We typically don't open submitted zip files, but we have some questions that could help out:

1. Which version of `cf-for-k8s` is this?
2. This sounds like a load-balancer problem. Referring to step 6 in https://github.com/cloudfoundry/cf-for-k8s/blob/develop/docs/deploy.md#steps-to-deploy , 

what's the output of this command?

`kubectl get svc -n istio-system istio-ingressgateway`

**Comment by arungskumar** [comment]
Thanks @ericpromislow 
Was using develop version for this build. Also noticed that, node resource group was not created due to permission issues. Trying to fix that and ll deploy the cluster again.

**Comment by Birdrock** [comment]
@arungskumar Have your issues been resolved?

**Comment by Birdrock** [comment]
Closed because the issue is stale. If there are further challenges, this issue can be reopened.

Birdrock & @jamespollard8
