### ISSUE TITLE
Log streaming in Stratos does not work

### ISSUE THREAD

**Issue by braunsonm** [cloudfoundry/cf-for-k8s#585]
## Describe the bug
Not sure if the bug should be reported here or on Stratos but Stratos works with regular CF Deployments so I reported here.

It seems that recent logs and log streaming does not work when connecting Stratos to a cf-for-k8s deployment.

## To Reproduce*
1. Deploy cf-for-k8s
2. Connect any recent Stratos instance to it (4.3.0 in my case)
3. Notice log streaming on every app does not work. Nothing appears.

## Expected behavior
Logs should be visible

## Additional context
`cf logs --recent` works fine.

### cf-for-k8s SHA 
cf-for-k8s v1.0.0 tag

### Cluster information
AKS

**Comment by richard-cox** [comment]
This may be similar to https://github.com/cloudfoundry/stratos/issues/4742, that case was specifically viewing logs of an application pushed via cf cli 7 and involves https://github.com/cloudfoundry/cf-for-k8s/issues/560 and https://github.com/cloudfoundry/stratos/issues/4741

**Comment by MasslessParticle** [comment]
This doesn't work because Stratos relies on the Firehose v1 api and cf-for-k8s does not implement the Firehose v1 or v2 APIs.

For convenience we've created:
https://github.com/cloudfoundry/stratos/issues/4832
