### ISSUE TITLE
As a developer, I would like to push CF applications with sidecar processes

### ISSUE THREAD

**Issue by braunsonm** [cloudfoundry/cf-for-k8s#597]
**Is your feature request related to a problem? Please describe.**
There are use cases where a sidecar process would be beneficial. Migrating from a traditional BOSH release of CF where this is supported makes a full migration impossible while it's unsupported.

**Describe the solution you'd like**
I would like CF Sidecars to work as documented here: https://docs.cloudfoundry.org/devguide/sidecars.html

**Describe alternatives you've considered**
There are no alternatives, especially while C2C networking is not supported.

**Comment by jamespollard8** [comment]
Closing as a duplicate of #390
