### ISSUE TITLE
Operator needs a mechanism to configure deployment attributes

### ISSUE THREAD

**Issue by XanderStrike** [cloudfoundry/cf-for-k8s#60]
As an operator deploying a foundation to my kubernetes cluster, I need to be able to configure the software I deploy to match the scale I intend for my foundation to reach, in code, so that my foundation is reproducible and I am not locked into a certain config unless I do kubectl commands.

**Background:**

Certain Istio components do not work well with the Horizontal Pod Autoscaler due to long lived connections continuing after a deployment is scaled horizontally. In our performance testing we find the best solution is to deploy the number of components necessary for peak usage at all times. The tradeoff in resource utilization is small compared to the cost of the service mesh control plane grinding to a halt during an upgrade.

https://cloudfoundry.slack.com/archives/CH9LF6V1P/p1583880458292900

CC @rosenhouse @ndhanushkodi @tcdowney @rodolfo2488

**Comment by jamespollard8** [comment]
Closing as stale. This is generally covered and more up-to-date under our active scaling epic.
