### ISSUE TITLE
PodDisruptionPolicy prevents Kubernetes upgrades

### ISSUE THREAD

**Issue by braunsonm** [cloudfoundry/cf-for-k8s#604]
## Describe the bug
This bug was discussed on Slack [here](https://cloudfoundry.slack.com/archives/CH9LF6V1P/p1608314156262800?thread_ts=1608311905.262000&cid=CH9LF6V1P), I'm just making an issue so that it isn't forgotten. If its already been fixed then please close!

An Istio `PodDisruptionPolicy` prevents upgrades to K8S since cf-for-k8s deploys only a single replica of `istiod`. This means that the node running `istiod` cannot be drained which will fail the upgrade. 

## To Reproduce*
1. Deploy cf-for-k8s 1.1
2. Attempt a kubernetes upgrade
3. Notice the node running istiod will never be drained

## Expected behavior
cf-for-k8s should deploy 2 replicas of istiod by default and 1 when running without resource constraints (for laptop/development deployments)

### cf-for-k8s SHA 
v1.1.0 tag

### Cluster information
AKS

**Comment by jamespollard8** [comment]
Thanks for the callout and great suggestion @braunsonm and @tcdowney. We fixed this in f63e71a9
