### ISSUE TITLE
Bump Istio to 1.8

### ISSUE THREAD

**Issue by braunsonm** [cloudfoundry/cf-for-k8s#622]
**Is your feature request related to a problem? Please describe.**
Istio 1.7 is entering EOL at the [end of next week](https://istio.io/latest/news/support/announcing-1.7-eol/). We are eager to use a Istio 1.9 feature which recently went GA. From what I understand Istio [should not](https://istio.io/latest/docs/setup/upgrade/) be updated across multiple minor revisions, so moving to 1.8 in the next cf-for-k8s release and then up again to 1.9 in a future cf-for-k8s release would be appreciated.

**Describe the solution you'd like**
Tested upgrade to Istio 1.8 with a future update to 1.9.

**Additional context**
Istio 1.7 support officially ends on February 19th.

**Comment by jamespollard8** [comment]
Thanks @braunsonm for the callout here. We'll bring this up to the team but we may not be able to complete this for several weeks.

Out of curiosity, which 1.9 feature(s) are you looking forward to?

cc my pair @jspawar

**Comment by braunsonm** [comment]
Understandable, more so just putting it on the radar.

As for the feature, some of our applications delegate authentication to an OAuth proxy, one for each app. We created a tool which adds C2C internal networking to cf-for-k8s for this purpose. The idea would be to use the new custom `AuthorizationPolicy` to replace the need for a proxy. Instead every app won't need it's own proxy and all traffic to the cluster (or selectively) will automatically go through the oauth flow if a bearer token is not provided. 

Info here: https://istio.io/latest/blog/2021/better-external-authz/

![](https://istio.io/latest/blog/2021/better-external-authz/external_authz.svg)

**Comment by bkrannich** [comment]
@braunsonm: Stumbled over your comment. Out of curiosity: Is it fair to say that you are trying to bring back a subset of CF Route Service use cases to cf-for-k8s? If so, could you share a bit more of how you do that?

**Comment by braunsonm** [comment]
@bkrannich Yea that's fair to say this would accomplish similar to what route services does. Since Istio can validate JWT tokens already, this extra functionality allows it to also send the user through the OAuth flow if they don't already have a token. We have some custom written code for adjusting some of what the Route Controller in cf-for-k8s does when apps spin up. Right now that means we allow apps to opt into allowing internal communication and/or blocking internet access for specific apps so that unsecured apps can only be reached through a proxy.

Istio 1.9 gives us a lot more flexibility to do this without rolling our own proxy and gives every app a single method for securing traffic before hitting the workload.

**Comment by jamespollard8** [comment]
@braunsonm and all,

As a heads up, our expectation is that upgrading to Istio v1.8 will likely break cf-for-k8s platform upgrades. Meaning your current foundation will need to be torn down (`kapp delete`'d) and then `kapp deploy`ed fresh, and all apps would need to be pushed anew. Our understanding is that these upgrade-breaking changes should stop at Istio v1.8

Is that your understanding as well? What expectations would you have from us / the product on top of bumping Istio and calling out the breaking changes and upgrade instructions via release notes?

**Comment by loewenstein** [comment]
@jamespollard8 would you mind elaborating more on the nature of update breaking changes through Istio 1.8 and how why this is going to stop after 1.8?

Is this related solely about upstream Istio breaking Update 1.7 -> 1.8 or is it the specific usage of Istio in the context of cf-for-k8s?

**Comment by jamespollard8** [comment]
Yeah, I should have done a better job qualifying what I wrote. I'm very uncertain about how the upgrade to Istio 1.8 is going to go. My worry about it breaking platform upgrades came mostly from:
1) historical trends (we had upgrade issues for the platform when jumping to istio v1.6 and v1.7, but unfortunately don't have great notes about the specific issues AND the specific people who worked on that have rotated teams/projects)
2) whispers/"water cooler chat" from the networking team several months ago. I remember hearing that major breaking changes were expected in Istio minor versions until 1.8 but some googling around hasn't helped me find anything useful to support that concept.

Tagging @XanderStrike @kauana @rodolfo2488 in case they have any context and/or can share any insight on how they might expect upgrading to istio v1.8 to go.

**Comment by XanderStrike** [comment]
The strategy for upgrading istio was to identify if anything in the [Upgrade Notes](https://istio.io/latest/news/releases/1.8.x/announcing-1.8/upgrade-notes/) might apply to us (I don't see anything, I think we've already disabled Mixer), then test it repeatedly and automate anything special we might've had to do. There's always gonna be a small amount of downtime as requests get routed to ingress gateways that are rolling, but well within the error budget we had.

Our goal was always to avoid at all costs reinstalling your foundation. I haven't looked at the 1.7 -> 1.8 upgrade personally, but you should be able to generate new Istio control plane configuration, kapp deploy it, and then `kubectl rollout restart` all workloads and system components with a job (see [here](https://github.com/cloudfoundry/cf-k8s-networking/blob/develop/doc/architecture-decisions/0016-job-for-upgrading-istio-sidecars-on-workloads.md)).

That's the theory anyway, it's only by testing it repeatedly that you'll discover issues.

**Comment by matt-royal** [comment]
Thanks, @XanderStrike. It sounds like the next steps on our side are to try using Istio 1.8+ and see if it works for us out of the box. If not, we'll pair with you to understand how to get past those issues.
