### ISSUE TITLE
ytt: Error: Overlaying data values on istio_static_ip

### ISSUE THREAD

**Issue by mtekasetya** [cloudfoundry/cf-for-k8s#660]
I'm following the installing tutorial cf-for-k8s on GKE. When performing the `ytt` command

`ytt -f config -f $TMP_DIR/cf-values.yml > $TMP_DIR/cf-for-k8s-rendered.yml`

I got the following error:

`ytt: Error: Overlaying data values (in following order: values/00-values.yml, values/10-images.yml, values/20-secrets-config-values.yml, values/30-experimental-values.yml, cf-values.yml):
  Document on line cf-values.yml:2:
    Map item (key 'istio_static_ip') on line cf-values.yml:540:
      Expected number of matched nodes to be 1, but was 0`

Not really familiar with `ytt`, should I add `istio_static_ip` into `values/00-values.yml`, `values/10-images.yml`, `values/20-secrets-config-values.yml`, `values/30-experimental-values.yml`, `cf-values.yml`?

**Comment by braunsonm** [comment]
Hey @mtekasetya 

The correct configuration in your `cf-values.yml` file should actually be
```yaml
load_balancer:
  static_ip: "EDIT ME"
```

Not `istio_static_ip`

**Comment by Birdrock** [comment]
@braunsonm Thanks for jumping in to answer.

@mtekasetya Hopefully the answer provided resolves your issue. Basically, ytt is expected to find a matched key to overlay the value into, but isn't finding it. The key was named in September (from `istio_static_ip`) [in this commit.](https://github.com/cloudfoundry/cf-for-k8s/commit/82aa48128877c89946cd9c369974553467704ede)
