### ISSUE TITLE
curl fails for docker apps

### ISSUE THREAD

**Issue by KesavanKing** [cloudfoundry/cf-for-k8s#77]
When we do `cf push <App Name> -o  <docker image>` all apps started running.

For few apps curl works but for some docker apps  failing with the following error

`upstream connect error or disconnect/reset before headers. reset reason: connection failure%`

Curl works for app:
`cloudfoundry/test-app`

Curl Doesn't work for :

`nginxdemos/hello`
The same app works in BOSH environment . It listens on port 80 
https://github.com/nginxinc/NGINX-Demos/blob/8d35696ec493bc5ba57930e9842ecf0e7db4911b/nginx-hello/hello.conf#L2

**Comment by jamespollard8** [comment]
Hey @KesavanKing thanks for reporting this! It looks like the same error captured by https://github.com/cloudfoundry-incubator/eirini-release/issues/147

> Deploying a docker app with Eirini only works if it uses port 8080.

We'll close this issue in favor of keeping conversation on the eirini-release issue.
