### ISSUE TITLE
System component communications are encrypted and mutually authenticated by Istio

### ISSUE THREAD

**Issue by shalako** [cloudfoundry/cf-for-k8s#86]
In CF for BOSH, security of communications between system components has been the responsibility of each component team. This requires offering endpoints that terminate TLS, configuration of certificates, and mechanism of rotation. It also requires logic for initiation of TLS handshakes with each remote endpoint that support them, and configuration of client certs for mutual auth with remote endpoints that support them.

In CF for K8s, all these responsibilities can be removed from component teams by leveraging Istio, which comes built-in with CF for K8s. Sidecars deployed with all pods will encrypt and mutually authenticate all intra-cluster communications, and certs will be generated and automatically rotated without burden on component teams.

- [Proposal for Credential Management in CF-for-K8s](https://docs.google.com/document/d/169dRpGbKJ7FC8ySR1hbWge08ED4ZOcROAVCx5XYKqbo/edit)
- [Proposal for Istio in CF-for-K8s](https://docs.google.com/document/d/1D12MZbZwVPSKmq97VNSNaoJbgUchM1xSC2VRIhXu7qU/edit)
- [Securing traffic in CF-for-K8s](https://github.com/cloudfoundry/cf-k8s-networking/blob/master/doc/architecture-decisions/0004-strategy-for-securing-network-traffic.md)
- [Ingress Routing to System Components in CF-fo-K8s](https://github.com/cloudfoundry/cf-k8s-networking/tree/master/doc/routing-to-sys-components)

This issue will be updated with example configuration for how to achieve this goal.

**Comment by paulcwarren** [comment]
Based on our [conversation](https://cloudfoundry.slack.com/archives/CFX13JK7B/p1604443729185200?thread_ts=1604432458.184300&cid=CFX13JK7B) in slack.  We believe that this is finished.
