### ISSUE TITLE
re-pushing an app that had successfully pushed previously fails

### ISSUE THREAD

**Issue by mwright-pivotal** [cloudfoundry/cf-for-k8s#88]
michaelwright@Michaels-iMac cruiseline-venues % cf push -f manifest-hql.yml                              
Pushing from manifest to org system / space alpha as admin...
Using manifest file /Users/michaelwright/Documents/Pivotal/Projects/cruiseline-venues/manifest-hql.yml
Deprecation warning: Use of 'buildpack' attribute in manifest is deprecated in favor of 'buildpacks'. Please see https://docs.cloudfoundry.org/devguide/deploy-apps/manifest-attributes.html#deprecated for alternatives and other app manifest deprecations. This feature will be removed in the future.

Getting app info...
Updating app with these attributes...
  name:                venue
  path:                /Users/michaelwright/Documents/Pivotal/Projects/cruiseline-venues/target/venue-0.0.1-SNAPSHOT.jar
  buildpacks:
+   https://github.com/cloudfoundry/java-buildpack
  disk quota:          1G
  health check type:   port
  instances:           1
  memory:              768M
  stack:               cflinuxfs3
  env:
    JBP_CONFIG_OPEN_JDK_JRE
    SPRING_PROFILES_ACTIVE
  routes:
    venue-busy-tasmaniandevil-qx.mesh.apps.pas.wrightcode.io

Updating app venue...
Unexpected Response
Response code: 500
CC code:       0
CC error code: 
Request ID:    25147124-0f66-4f93-966d-438546df1e13::8240f21e-4d96-460d-8103-a452e47d551f
Description:   {
  "error_code": "UnknownError",
  "description": "An unknown error occurred.",
  "code": 10001
}

FAILED

From capi-api-server logs:

{"timestamp":1585166122.571469,"message":"Request failed: 500: {\"error_code\"=>\"UnknownError\", \"description\"=>\"An unknown error occurred.\", \"code\"=>10001, \"test_mode_info\"=>{\"description\"=>\"undefined method `buildpacks=' for #<VCAP::CloudController::KpackLifecycleDataModel:0x00007fe0903cc170>\\nDid you mean?  buildpacks\", \"error_code\"=>\"CF-buildpacks=\", \"backtrace\"=>[\"/cloud_controller_ng/app/actions/v2/app_update.rb:75:in `update_lifecycle'\", \"/cloud_controller_ng/app/actions/v2/app_update.rb:25:in `block in update'\", \"/usr/local/lib/ruby/gems/2.5.0/gems/sequel-5.22.0/lib/sequel/database/transactions.rb:258:in `_transaction'\", \"/usr/local/lib/ruby/gems/2.5.0/gems/sequel-5.22.0/lib/sequel/database/transactions.rb:233:in `block in transaction'\", \"/usr/local/lib/ruby/gems/2.5.0/gems/sequel-5.22.0/lib/sequel/connection_pool/threaded.rb:92:in `hold'\", \"/usr/local/lib/ruby/gems/2.5.0/gems/sequel-5.22.0/lib/sequel/database/connecting.rb:270:in `synchronize'\", \"/usr/local/lib/ruby/gems/2.5.0/gems/sequel-5.22.0/lib/sequel/database/transactions.rb:199:in `transaction'\", \"/cloud_controller_ng/app/actions/v2/app_update.rb:13:in `update'\", \"/cloud_controller_ng/app/controllers/runtime/apps_controller.rb:291:in `update'\", \"/cloud_controller_ng/app/controllers/base/base_controller.rb:84:in `dispatch'\", \"/cloud_controller_ng/lib/cloud_controller/rest_controller/routes.rb:16:in `block in define_route'\", \"/usr/local/lib/ruby/gems/2.5.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:1634:in `call'\", \"/usr/local/lib/ruby/gems/2.5.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:1634:in `block in compile!'\", \"/usr/local/lib/ruby/gems/2.5.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:992:in `block (3 levels) in route!'\", \"/usr/local/lib/ruby/gems/2.5.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:1011:in `route_eval'\"

**Comment by cwlbraa** [comment]
Hi! cf-for-k8s does not support setting buildpacks yet or any other form of customizing the buildpack autodetect flow. Can you try removing `buildpacks:` from your manifest?

**Comment by mwright-pivotal** [comment]
ah I didn't even think of that when I picked this app... yes, I have the old school buildpack referenced.  removing from the manifest allowed me to re-push the app.

I guess this validation isn't done on the initial push?

Anyway, we can close this issue.  Thanks!

**Comment by cwlbraa** [comment]
thus far we haven't been writing validation logic for any of the "TBD" features in cf-for-k8s.

**Comment by pivotaljohn** [comment]
> I guess this validation isn't done on the initial push?

Yeah... at this time (i.e. pre-alpha), one can expect there to be all kinds of sharp edges.  We try to signal that when we say,  "This is a highly experimental project..."

**Comment by selzoc** [comment]
may be related to https://github.com/cloudfoundry/capi-k8s-release/issues/25

**Comment by domdom82** [comment]
@selzoc the restage problem is actually fixed now, however this issue (re-push existing app w/ buildpack keyword) still exists. So they are rather unrelated I guess.

**Comment by selzoc** [comment]
@domdom82 true!  that feature is not implemented yet.  You can follow this placeholder story if you want to track it: https://www.pivotaltracker.com/story/show/171029528
