### ISSUE TITLE
CF installation script is not idempotent: errors out on Istio ingress-gateway Service re-application

### ISSUE THREAD

**Issue by emalm** [cloudfoundry/cf-for-k8s#91]
### Summary

Re-running `./bin/install-cf.sh` with the same input values after a successful installation should be a trivial update, but instead fails on applying configuration to the Istio ingress-gateway Service.

### Reproduction steps

- K8s target: K8s v1.15.5, provisioned via Enterprise PKS v1.6.1 on vSphere with networking integration with NSX-T (and hence support for K8s Services of type `LoadBalancer`).
- cf-for-k8s @ https://github.com/cloudfoundry/cf-for-k8s/commit/04660d57112daa1ff89af29077728c31e94c65d3 (head of master at time of writing).

```
$ ./bin/install-cf.sh ~/workspace/environments/haas-410/credentials-cf-values.yml
Target cluster 'https://cf-k8s.haas-410.pez.pivotal.io:8443' (nodes: cd3174a3-f552-42fb-b409-55a1c57cd354, 2+)

Changes

Namespace             Name                                                    Kind                          Conds.  Age  Op      Wait to    Rs  Ri
(cluster)             adapters.config.istio.io                                CustomResourceDefinition      -       -    create  reconcile  -   -
...(snip)...
11:34:45AM: ok: reconcile deployment/log-cache (apps/v1) namespace: cf-system
11:34:45AM: ---- applying complete [234/234 done] ----
11:34:45AM: ---- waiting complete [234/234 done] ----

Succeeded
```
```
$ ./bin/install-cf.sh ~/workspace/environments/haas-410/credentials-cf-values.yml
Target cluster 'https://cf-k8s.haas-410.pez.pivotal.io:8443' (nodes: cd3174a3-f552-42fb-b409-55a1c57cd354, 2+)

Changes

Namespace             Name                               Kind            Conds.  Age  Op      Wait to    Rs  Ri
cf-workloads-staging  cc-kpack-registry-service-account  ServiceAccount  -       5m   update  reconcile  ok  -
istio-system          istio-ingressgateway               Service         -       5m   update  reconcile  ok  -

Op:      0 create, 0 delete, 2 update, 0 noop
Wait to: 2 reconcile, 0 delete, 0 noop

11:38:23AM: ---- applying 2 changes [0/2 done] ----
11:38:23AM: update serviceaccount/cc-kpack-registry-service-account (v1) namespace: cf-workloads-staging
11:38:23AM: update service/istio-ingressgateway (v1) namespace: istio-system

kapp: Error: Applying update service/istio-ingressgateway (v1) namespace: istio-system: Updating resource service/istio-ingressgateway (v1) namespace: istio-system: Service "istio-ingressgateway" is invalid: spec.healthCheckNodePort: Invalid value: 0: cannot change healthCheckNodePort on loadBalancer service with externalTraffic=Local during update (reason: Invalid)
```

### Expected behavior

Although workflows to change configuration parameters are not yet supported for cf-for-k8s, I expected to be able to re-apply the same configuration to an existing cf-for-k8s deployment and for it to be a trivially successful null operation.

**Comment by jamespollard8** [comment]
Interesting - I hadn't seen this behavior with GKE or AKS. It'd be great to establish if this is PKS only.

> with networking integration with NSX-T (and hence support for K8s Services of type LoadBalancer)

Eric, what is generally involved with this setup? Just changes on the infrastructure side?

Also, what's the difference between the 2 snippets you shared? I see that one of the paths includes `pas-wok-acceptance` - were they intended to be identical?

**Comment by emalm** [comment]
@jamespollard8 Right, after [installing a default StorageClass configured to provision vSphere volumes](https://docs.pivotal.io/pks/1-6/volumes.html#dynamic-pv-deployment), I've been able to deploy cf-for-k8s unmodified (now that #84 has been merged in to resolve #69).

I've relied on the Pivotal PEZ team to provide a pre-provisioned PKS+NSX-T environment on vSphere in one of their Hardware-as-a-Service slots, since installing NSX-T itself is pretty complicated. I haven't tried this yet, but it would be interesting to know whether the same issue happens with PKS on one of the supported public clouds (AWS, Azure, GCP), as my understanding is that they also integrate with the underlying cloud platform to realize LoadBalancer Services via the available LBaaS.

And yes, those paths were intended to be identical: I simplified the first one, but not the second. 🤦‍♂ Fixed!

**Comment by acosta11** [comment]
This might also be fixed by the kapp rebase rule for Services in cf2a505. To make sure we don't close this prematurely in the case of another symptom beyond the included logs, do you mind doing another check with the latest master @emalm ?

**Comment by emalm** [comment]
Thanks, @acosta11! I've tried this with https://github.com/cloudfoundry/cf-for-k8s/commit/e70e03fe925cfbea8d753115a204975c9cbf9bbe against the same K8s cluster as before, and while `install-cf.sh` still tries to update the istio-ingressgateway Service it now succeeds. For context, here's the output after adding a ` --diff-changes` to the `kapp` arguments:

```
Target cluster 'https://cf-k8s.haas-410.pez.pivotal.io:8443' (nodes: cd3174a3-f552-42fb-b409-55a1c57cd354, 4+)

--- update serviceaccount/cc-kpack-registry-service-account (v1) namespace: cf-workloads-staging
  ...
 14, 14   - name: cc-kpack-registry-auth-secret
 15     - - name: cc-kpack-registry-service-account-token-2bkjz
 16, 15
--- update service/istio-ingressgateway (v1) namespace: istio-system
  ...
  2,  2   metadata:
  3     -   annotations:
  4     -     ncp/internal_ip_for_policy: 100.64.16.7
  5,  3     creationTimestamp: "2020-04-09T00:50:20Z"
  6,  4     labels:
  ...
 23, 21     - name: status-port
 24     -     nodePort: 31636
 25, 22       port: 15020
 26     -     protocol: TCP
 27, 23       targetPort: 15020
 28, 24     - name: http2
 29     -     nodePort: 31137
 30, 25       port: 80
 31     -     protocol: TCP
 32, 26       targetPort: 80
 33, 27     - name: https
 34     -     nodePort: 32408
 35, 28       port: 443
 36     -     protocol: TCP
 37     -     targetPort: 443
 38, 29     - name: kiali
 39     -     nodePort: 30384
 40, 30       port: 15029
 41     -     protocol: TCP
 42, 31       targetPort: 15029
 43, 32     - name: prometheus
 44     -     nodePort: 32230
 45, 33       port: 15030
 46     -     protocol: TCP
 47, 34       targetPort: 15030
 48, 35     - name: grafana
 49     -     nodePort: 32304
 50, 36       port: 15031
 51     -     protocol: TCP
 52, 37       targetPort: 15031
 53, 38     - name: tracing
 54     -     nodePort: 32035
 55, 39       port: 15032
 56     -     protocol: TCP
 57, 40       targetPort: 15032
 58, 41     - name: tls
 59     -     nodePort: 30478
 60, 42       port: 15443
 61     -     protocol: TCP
 62, 43       targetPort: 15443
 63, 44     selector:
  ...
 65, 46       kapp.k14s.io/app: "1586393273791178000"
 66     -   sessionAffinity: None
 67, 47     type: LoadBalancer
 68, 48   status:

Changes

Namespace             Name                               Kind            Conds.  Age  Op      Wait to    Rs  Ri
cf-workloads-staging  cc-kpack-registry-service-account  ServiceAccount  -       3h   update  reconcile  ok  -
istio-system          istio-ingressgateway               Service         -       3h   update  reconcile  ok  -

Op:      0 create, 0 delete, 2 update, 0 noop
Wait to: 2 reconcile, 0 delete, 0 noop

9:25:42PM: ---- applying 2 changes [0/2 done] ----
9:25:42PM: update serviceaccount/cc-kpack-registry-service-account (v1) namespace: cf-workloads-staging
9:25:42PM: update service/istio-ingressgateway (v1) namespace: istio-system
9:25:43PM: ---- waiting on 2 changes [0/2 done] ----
9:25:44PM: ok: reconcile serviceaccount/cc-kpack-registry-service-account (v1) namespace: cf-workloads-staging
9:25:44PM: ok: reconcile service/istio-ingressgateway (v1) namespace: istio-system
9:25:44PM: ---- applying complete [2/2 done] ----
9:25:44PM: ---- waiting complete [2/2 done] ----

Succeeded
```

All of those changes to the Service seem like either defaults (`protocol: TCP`, `sessionAffinity: None`) or inferred values (`targetPort: 443`) that are made explicit in the K8s API, or dynamic values that K8s has added to the spec (all the `nodePort` values, or the NCP annotation), and their application doesn't seem to affect the Service itself.

**Comment by acosta11** [comment]
Thanks for the confirmation! And your explanation regarding the remainder of the diff are consistent with our understanding. We'll go ahead and close this issue out.
