### ISSUE TITLE
`sample-cf-install-values.yml` is not updated to the recent changes in registry config names

### ISSUE THREAD

**Issue by Syerram** [cloudfoundry/cf-for-k8s#96]
## Expected behavior
`sample-cf-install-values.yml` is matches to the config information generated by `generate-values.sh` [1](https://github.com/cloudfoundry/cf-for-k8s/blob/master/hack/generate-values.sh#L250)

## Actual behavior
`sample-cf-install-values.yml` still contains old registry config names and will result in an error when user does not use `generate-values.sh`

## Context
Please Check-in with Dave Walter and Andrew Costa for additional context.

**Comment by cppforlife** [comment]
seems like it was fixed in https://github.com/cloudfoundry/cf-for-k8s/commit/d6252e2c89e2224742a0c55a40573866332ae3c9
