### ISSUE TITLE
suggestion: share guid between cf app and docker registry 

### ISSUE THREAD

**Issue by odedia** [cloudfoundry/cf-for-k8s#98]
When an app is deployed to cf, it receives a GUID that can be identified by running:
`cf app my-app --guid`

When an app is deployed to cf-for-k8s, it also saves the image in a docker registry with a generated image name.
It would be useful for troubleshooting and tracking to have these two items share the same identifier, or have a label or other mechanism to match the two.

Right now they appear to be  different:
```
cf app todo-service --guid
bd1abc1a-ed73-429d-ba2c-a68e18ca5428
```

While the corresponding image in the docker registry (harbor in my case) is :
```
odedia/5517b767-e03b-4129-a38e-f6654c79adc2
```

Thanks!

**Comment by jamespollard8** [comment]
Oh interesting, I just confirmed this on GCR as well. The app guid is nicely applied as a label and annotation in a few places on the pod:
```
# describe the app pod
Labels:       cloudfoundry.org/app_guid=e0e0bd49-f407-4d25-8d6d-4c9383c29462
              cloudfoundry.org/guid=e0e0bd49-f407-4d25-8d6d-4c9383c29462
...
Annotations:  cloudfoundry.org/application_id: e0e0bd49-f407-4d25-8d6d-4c9383c29462
```

But the app guid is not used in the image name.

@cloudfoundry/cf-capi have you already considered this? We're definitely interested in hearing your opinion (or plan?) here.

Thanks!
release integration

**Comment by selzoc** [comment]
Yes, please see https://github.com/cloudfoundry/capi-k8s-release/issues/19 - we plan to make one oci image per app, identified via the app guid, and with tags to distinguish between builds.  The current behavior is to name the image with the guid of the package that was given to kpack to build into the image, but that will change.

**Comment by ericpromislow** [comment]
Closing this as a relint issue; please see [cloudfoundry/capi-k8s-release#19](https://github.com/cloudfoundry/capi-k8s-release/issues/19)
