### ISSUE TITLE
Upgrading cf-for-k8s to a new version fails

### ISSUE THREAD

**Issue by Syerram** [cloudfoundry/cf-for-k8s#99]
## Expected behavior
When I upgrade cf-for-k8s to a new version, I expect the upgrade to complete successfully.

## Actual behavior
When I upgraded cf-for-k8s to the latest master, it failed.

## Workaround
Delete the foundation and reinstall CF.

## Context
This is a known issue and will be tackled post 0.1 release.

**Comment by paulcwarren** [comment]
Closing as we regularly perform upgrades in our pipelines now.
